### ISSUE TITLE
录音

### ISSUE THREAD

**Issue by zhageww** [wzpan/wukong-robot#1]
大佬您好：
       之前在群里看到您在写新项目，今天看到有更新，于是follow了一下。看了下源码准备学习一下，来优化我自己之前写的语音机器人。我的机器人录音的时候有点慢，要等一段时间才可以录音，所以想看看大佬是如何处理的，结果看了半天没有找到录音的代码。不知道您是用的软件录音还是自己用python的呢？望大佬指点一下迷津！

**Comment by wzpan** [comment]
@zhageww 我使用的是PyAudio来进行录音，而且直接复用了snowboy项目给的[基础范例](https://github.com/wzpan/snowboy/blob/master/examples/Python3/demo4.py)。

**Comment by zhageww** [comment]
明白了，多谢大佬。
