### ISSUE TITLE
你好,遇到一个问题:离线唤醒机制初始化失败：[Errno -9996] Invalid input device (no default output device)

### ISSUE THREAD

**Issue by FanXingGuo** [wzpan/wukong-robot#10]
(venv) pi@raspberrypi:~/wukong $ python3 wukong.py

********************************************************
*          wukong-robot - 中文语音对话机器人           *
*          (c) 2019 潘伟洲 <m@hahack.com>              *
*     https://github.com/wzpan/wukong-robot.git        *
********************************************************

            如需退出，可以按 Ctrl-4 组合键。

2019-02-17 05:03:38,723 - server.server - CRITICAL - 服务器启动失败: [Errno 98] Address already in use
CRITICAL:server.server:服务器启动失败: [Errno 98] Address already in use
WARNING:robot.config:silent_threshold not specified in profile, defaulting to '15'
WARNING:robot.config:recording_timeout not specified in profile, defaulting to '5'
ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_plug.c:1261:(_snd_pcm_plug_open) Unknown field rate
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
2019-02-17 05:03:39,609 - __main__ - CRITICAL - 离线唤醒机制初始化失败：[Errno -9996] Invalid input device (no default output device)
CRITICAL:__main__:离线唤醒机制初始化失败：[Errno -9996] Invalid input device (no default output device)

**Comment by wzpan** [comment]
你可能启动多个 wukong-robot 了。

**Comment by wzpan** [comment]
另外，贴 log 最好头尾都用三个反斜杆（`) 括起来。

**Comment by bingws** [comment]
I have the same problem on Ubuntu16.04, how to solve it ?
