### ISSUE TITLE
在斐讯n1盒子上安装之后，语音唤醒之后，不能对话

### ISSUE THREAD

**Issue by Jesse54211** [wzpan/wukong-robot#104]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装/docker安装

**操作系统**

（例如 Raspbian Stretch、Ubuntu 16.04）

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

具体说明下问题
报错如下

INFO:snowboy:Keyword 1 detected at time: 2020-01-26 06:51:03
INFO:__main__:开始录音
INFO:robot.Conversation:结束录音
INFO:robot.ASR:baidu-asr 语音识别到了：['哦哦，清除缓存，']
CRITICAL:robot.Conversation:Expecting value: line 1 column 1 (char 0)
就没反应了，再次唤醒，还是同样问题

**Comment by wzpan** [comment]
@Jesse54211 请更新到最新的2.1.2。新版本我增加了更多log，方便更详细的定位问题。

**Comment by Jesse54211** [comment]
好的 谢谢
