### ISSUE TITLE
在树莓派3b中运行wukong.py遇到问题"No module named 'aiy'"

### ISSUE THREAD

**Issue by HYJJJJJJJJ** [wzpan/wukong-robot#108]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装

**操作系统**

Raspbian buster

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

通过python3 wukong.py运行应用，会卡在
********************************************************
*          wukong-robot - 中文语音对话机器人           *
*          (c) 2019 潘伟洲 <m@hahack.com>              *
*     https://github.com/wzpan/wukong-robot.git        *
********************************************************

            后台管理端：http://0.0.0.0:5000
            如需退出，可以按 Ctrl-4 组合键

Unhandled exception in thread started by <bound method Wukong._init_aiy_button_event of <__main__.Wukong object at 0x72585f70>>
Traceback (most recent call last):
  File "wukong.py", line 106, in _init_aiy_button_event
    from aiy.board import Board
ModuleNotFoundError: No module named 'aiy'

web端能够访问

**Comment by wzpan** [comment]
检查下配置是不是把 LED 开了？

``` yaml
# 是否展示灯光效果
# 支持 Respeaker 2 Mics 和 Google AIY Voice Kit 两种
# 必须具备相应的硬件和驱动
LED:
    enable: false
    type: aiy  # aiy: Google AIY Voice Kit; respeaker：respeaker 2Mics
```

只有用了 AIY Voice Kit 或者 respeaker 2 Mics 才能开。否则请把 `enable` 设为 `false`。

**Comment by HYJJJJJJJJ** [comment]
> 检查下配置是不是把 LED 开了？
> 
> ```yaml
> # 是否展示灯光效果
> # 支持 Respeaker 2 Mics 和 Google AIY Voice Kit 两种
> # 必须具备相应的硬件和驱动
> LED:
>     enable: false
>     type: aiy  # aiy: Google AIY Voice Kit; respeaker：respeaker 2Mics
> ```
> 
> 只有用了 AIY Voice Kit 或者 respeaker 2 Mics 才能开。否则请把 `enable` 设为 `false`。

大佬您好，我用的是respeaker 2 Mics，然后我把LED关掉之后，ssh界面就会直接卡在********************************************************
*          wukong-robot - 中文语音对话机器人           *
*          (c) 2019 潘伟洲 <m@hahack.com>              *
*     https://github.com/wzpan/wukong-robot.git        *
********************************************************

            后台管理端：http://0.0.0.0:5000
            如需退出，可以按 Ctrl-4 组合键

进入web端的log界面后能够见到各个部分组件启用禁用的状态，但是在开句那句“师傅你好.......”后，音箱尽管生成了语音，但仍然无法进行语音应答
2020-02-24 05:11:53,824 - robot.AI - AI.py - chat - line 135 - INFO - emotibot 回答：我是叮当，叮当就是我，oh yeah。
2020-02-24 05:11:54,250 - robot.TTS - TTS.py - get_speech - line 151 - INFO - baidu-tts 语音合成成功，合成路径：/tmp/tmpdt1nm3bv.mp3
2020-02-24 05:11:54,252 - robot.Conversation - Conversation.py - say - line 197 - INFO - True
2020-02-24 05:11:54,254 - robot.Conversation - Conversation.py - say - line 199 - INFO - onSay: 我是叮当，叮当就是我，oh yeah。, http://0.0.0.0:5000/audio/d491c35e546a491dfaa0aa874ab7f2ba.mp3

使用ps命令查看后台进程，检测到多个CMD项为“play”的进程，请问您清楚这是什么问题导致的嘛？

**Comment by HYJJJJJJJJ** [comment]
结束进程后，直接进入temp目录下，使用play命令播放缓存的语音，能够得到正确的语音响应。

**Comment by HYJJJJJJJJ** [comment]
经过尝试，snowboy离线唤醒能够正常使用，第一次离线唤醒后，语音转文字，机器人交互，文字转语音都正常，但是似乎由于无法播放音频，第二次开始，就算离线唤醒被触发，系统也不会开始主动录音，log如下：

INFO:snowboy:Keyword 1 detected at time: 2020-02-24 06:20:52
INFO:__main__:开始录音
INFO:robot.Conversation:结束录音
INFO:robot.ASR:baidu-asr 语音识别到了：['嗯，']
INFO:robot.AI:emotibot 回答：换个其他的话题吧，我对你的生活比较感兴趣呢~
INFO:robot.TTS:baidu-tts 语音合成成功，合成路径：/tmp/tmpjpngyulw.mp3
INFO:snowboy:Keyword 1 detected at time: 2020-02-24 06:22:47

**Comment by Aa1136837555** [comment]
我也碰到这个情况，请问层主是怎么解决掉缺少aiy这个模块的

**Comment by wzpan** [comment]
> 大佬您好，我用的是respeaker 2 Mics

对于 2 mics ，可以用这个配置：

``` yaml
# 是否展示灯光效果
# 支持 Respeaker 2 Mics 和 Google AIY Voice Kit 两种
# 必须具备相应的硬件和驱动
LED:
    enable: false
    type: respeaker  # aiy: Google AIY Voice Kit; respeaker：respeaker 2Mics
```
