### ISSUE TITLE
处理逻辑

### ISSUE THREAD

**Issue by nameluck** [wzpan/wukong-robot#11]
问题一：
       我按照文档所说的，语音输入："写诗"，始终得到一个反馈，“您是不是盗墓笔记看多了”，不是文档所描述的诗歌，也就是说应该没有触发写诗这项技能，是不是直接送给图灵机器人了？

问题二：
       我有点不清楚处理逻辑，您可不可以讲一下您的处理逻辑呀，我说的话录音，stt转变成文本，此时这段文本是匹配技能呢，还是送给图灵机器人呢？

问题三
       我将百度语音的appid api key换成了我自己的，就不能实现查询天气了，我记得我之前在网页端测试图灵机器人的时候，输入我的地址及天气关键词是可以出现本地天气的呀。

**Comment by wzpan** [comment]
1. 如果你已经升级到比较新的版本，而且发现没有这个技能，那就是因为 baidu unit 今天的使用次数已经被用完。明天再试试吧。
2. 先匹配，匹配不到再走机器人兜底闲聊。
3. 检查下是不是打开了 Weather 插件，而心知天气也有频率限制。你可以关闭这个插件再试。

**Comment by wzpan** [comment]
问题1确认是Poem插件在最近一次接口重构中遗漏了修改导致没有生效。已发布1.2.3修复了这个问题。

**Comment by ZhangJun1015** [comment]
在MacBookAir安装成功，可以唤醒。
1、cp default.yml $home/.config.yml 之后，修改百度api，邮箱，天气等内容。
和孙悟空交互时，怎么知道我使用的是default.yml，还是config.yml的设置呢？
2、唤醒孙悟空后，在终端按下Ctrl-4组合键，只有咚的一声响，没有任何文字提示吗？
我怎么知道是否退出了呢？也没有弹出诸如 “Python 已停止工作” 的警告。
还有所谓的前台工作和后台工作是什么意思？如何区分？
谢谢！

**Comment by nameluck** [comment]
用的是config.yml里面的设置吧，如果你用自己的百度api的话，百度语音控制台有统计数据呀，截至到某天某时，语音识别服务被访问了多少次

**Comment by ZhangJun1015** [comment]
> 用的是config.yml里面的设置吧，如果你用自己的百度api的话，百度语音控制台有统计数据呀，截至到某天某时，语音识别服务被访问了多少次

去百度语音后台看了一下，0次，刚才升级了1.2.3，试了一下“写诗”，还是回答我“盗墓笔记看多了”。应该没调用config.yml

**Comment by nameluck** [comment]
那个百度语音后台更新不是实时的，你过一两个小时再看。

**Comment by wzpan** [comment]
> 和孙悟空交互时，怎么知道我使用的是default.yml，还是config.yml的设置呢？

如果有 `config.yml` ，则只用 `config.yml` ；如果没有，则读自带的默认配置 `default.yml`（不推荐，如果修改，会影响更新）。

> 2、唤醒孙悟空后，在终端按下Ctrl-4组合键，只有咚的一声响，没有任何文字提示吗？

这是 Python 的强杀功能，都已经强杀，怎么可能有提示？

> 我怎么知道是否退出了呢？也没有弹出诸如 “Python 已停止工作” 的警告。

``` sh
ps -auwx | grep wukong
```

就知道有没有 wukong 的进程在跑。

如果是这样子：

```
pi@raspberrypi:~/docs $ ps auwx | grep wukong
pi        4319  0.0  0.0   4580   536 pts/6    S+   00:57   0:00 grep --color=auto wukong
```

说明没有。唯一一个进程就是你刚刚执行的 ps 命令。并且执行完就自动结束了。

如果是这样子：

```
pi@raspberrypi:~/wukong-robot$ ps auwx | grep wukong
pi        4326 55.2  4.2 405240 38180 pts/6    Sl+  00:58   0:07 python3 wukong.py
pi        4350  0.0  0.0   4580   548 pts/1    S+   00:59   0:00 grep --color=auto wukong 
```

说明有。你可以明显看到有个 `python3 wukong.py` 的进程。比如，对于上面，我要杀掉进程的话，只需要 `kill 4326` 。要注意这个 `4326` 是那一刻 wukong-robot 的 PID 号，不是固定的。

> 还有所谓的前台工作和后台工作是什么意思？如何区分？

* 如果你能找到你启动 wukong-robot 的界面，并且能看到 log ，就说明已经就在前台。
* 如果你是用 tmux 或者简单通过 `python3 wukong.py &` 启动的，或者你开了一堆的 terminal，有一个刚好启动了 wukong-robot ，而你浑然不知。此时启动怎么都报 -9996，通过 `ps` 命令确实看到一个 `python3 wukong.py` 的进程，那么这个进程对你而言就是一个后台进程（就像有个人在幕后操作）。

ps：这些都是 Linux 的使用基础。建议好好学一下。

**Comment by wzpan** [comment]
> > 和孙悟空交互时，怎么知道我使用的是default.yml，还是config.yml的设置呢？
> 
> 如果有 `config.yml` ，则只用 `config.yml` ；如果没有，则读自带的默认配置 `default.yml`（不推荐，如果修改，会影响更新）。
> 
> > 2、唤醒孙悟空后，在终端按下Ctrl-4组合键，只有咚的一声响，没有任何文字提示吗？
> 
> 这是 Python 的强杀功能，都已经强杀，怎么可能有提示？
> 
> > 我怎么知道是否退出了呢？也没有弹出诸如 “Python 已停止工作” 的警告。
> 
> ```shell
> ps -auwx | grep wukong
> ```
> 
> 就知道有没有 wukong 的进程在跑。
> 
> 如果是这样子：
> 
> ```
> pi@raspberrypi:~/docs $ ps auwx | grep wukong
> pi        4319  0.0  0.0   4580   536 pts/6    S+   00:57   0:00 grep --color=auto wukong
> ```
> 说明没有。唯一一个进程就是你刚刚执行的 ps 命令。并且执行完就自动结束了。
> 
> 如果是这样子：
> 
> ```
> pi@raspberrypi:~/wukong-robot$ ps auwx | grep wukong
> pi        4326 55.2  4.2 405240 38180 pts/6    Sl+  00:58   0:07 python3 wukong.py
> pi        4350  0.0  0.0   4580   548 pts/1    S+   00:59   0:00 grep --color=auto wukong 
> ```
> 说明有。你可以明显看到有个 `python3 wukong.py` 的进程。比如，对于上面，我要杀掉进程的话，只需要 `kill 4326` 。要注意这个 `4326` 是那一刻 wukong-robot 的 PID 号，不是固定的。
> 
> > 还有所谓的前台工作和后台工作是什么意思？如何区分？
> 
> * 如果你能找到你启动 wukong-robot 的界面，并且能看到 log ，就说明已经就在前台。
> * 如果你是用 tmux 或者简单通过 `python3 wukong.py &` 启动的，或者你开了一堆的 terminal，有一个刚好启动了 wukong-robot ，而你浑然不知。此时启动怎么都报 -9996，通过 `ps` 命令确实看到一个 `python3 wukong.py` 的进程，那么这个进程对你而言就是一个后台进程（就像有个人在幕后操作）。
> 
> ps：这些都是 Linux 的使用基础。建议好好学一下。

**Comment by ZhangJun1015** [comment]
早上好，汇报使用情况：
1、百度语音还是没有统计；
2、在终端按下Ctrl + 4组合键没有用。按完之后，孙悟空还没死，新建窗口用ps auwx | grep wukong还是看到两个进程。可以用kill杀掉。

**Comment by wzpan** [comment]
1. `cp default.yml $home/.config.yml` ? 这是你的命令？这里错了。
2. 什么操作系统？按完之后，如果能敲命令，肯定就死了。看到进程，那就是其他的地方开启的。你还可以试试 Ctrl-\ 命组合键。

**Comment by nameluck** [comment]
为什么不用唤醒词"孙悟空"也能唤醒呀，我说“嘿嘿嘿嘿嘿嘿嘿"一样也唤醒了他

**Comment by ZhangJun1015** [comment]
> * `cp default.yml $home/.config.yml` ? 这是你的命令？这里错了。
> * 什么操作系统？按完之后，如果能敲命令，肯定就死了。看到进程，那就是其他的地方开启的。你还可以试试 Ctrl-\ 命组合键。
1、config.yml起作用了，原因是我把.wukong文件夹的位置弄错了；
2、使用Ctrl + \ 退出是可以的，弹出python意外的对话框。ctrl + 4 还是不行，不纠结了；
3、使用MacOS Mojave 10.14.2，默认终端。没有外接麦克风，需要喊多次才有一次响应。回应的速度大概要等1～2秒才有回话。
4、这是config.yml的天气设置，问悟空“深圳天气”，报错：
```
# 天气
# 使用心知天气的接口
# https://www.seniverse.com/
weather:
    enable: true
    key: 'mxyn5aekn8s4kcee'
    location: '深圳'
```
报错信息：
```
2019-02-18 10:21:33,948 - Weather - ERROR - name 'result' is not defined
ERROR:Weather:name 'result' is not defined
```

**Comment by wzpan** [comment]
@nameluck @ZhangJun1015 本单已经OT太多。请重新提单。一般是一个问题提一个单。

**Comment by wzpan** [comment]
@ZhangJun1015 Weather插件有bug，已fixed。并发了1.2.2版本的contrib。
