### ISSUE TITLE
报错CRITICAL:robot.Conversation:nothing to repeat at position 0

### ISSUE THREAD

**Issue by wave2018** [wzpan/wukong-robot#110]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装

**操作系统**
raspbian（buster）

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

语音录入后报错：
CRITICAL:robot.Conversation:nothing to repeat at position 0
后台日志显示：robot.Conversation - Conversation.py - doConverse - line 128 - CRITICAL - nothing to repeat at position 0
报错之后软件无响应，一切回复/技能均无法使用;开头处自动语音打招呼不受影响

**复现步骤**

每次录音

**Comment by wzpan** [comment]
换个ASR服务试试

**Comment by wzpan** [comment]
久无回复，先关闭了。如果有问题可继续提问。
