### ISSUE TITLE
树莓派4B上反应速度慢

### ISSUE THREAD

**Issue by Zmjcc** [wzpan/wukong-robot#111]
您好，我在树莓派4B（装respeaker2麦克风阵列）上运行该程序时，在正确说出离线唤醒词后麦克风上的指示灯能很快反应，但录音提示音和开始录音的log要隔较久的时间才会播放出来，请问有没有什么改善策略？

**Comment by wzpan** [comment]
试试自己注册个百度开发者账号，使用极速版百度ASR

**Comment by Zmjcc** [comment]
您好，可能我没有把问题描述清楚，我指的是离线唤醒后的callback函数执行上的问题，snowboy检测到热词按理应该是respeaker上的指示灯亮且此时立即开始录音，但奇怪的是我的树莓派在运行时灯亮后到听到ding的一声开始录音之间由明显的一段时间间隔。
就是这两句话之间：
INFO:snowboy:Keyword 1 detected at time: 2020-03-16 19:44:55
INFO:__main__:开始录音

**Comment by wzpan** [comment]
试试去掉respeaker的指示灯效果。看看有没有改善。

从代码上看，respeaker 亮灯指令后立马就是播放“ding”的一声。

``` python
...
    if config.get('/LED/enable', False):
        LED.wakeup()
    Player.play(constants.getData('beep_hi.wav'), onCompleted=start_record, wait=True)
...
```

**Comment by Kevin369** [comment]
Zmjcc大佬想问下，树莓派上安装完成wukong-robot,以后还后台发送信息是可以收到回复和语音文件生成的，语音播放是自动播放吗？唤醒树莓派需要接入语音模块吗？

**Comment by hanyanze** [comment]
> 您好，我在树莓派4B（装respeaker2麦克风阵列）上运行该程序时，在正确说出离线唤醒词后麦克风上的指示灯能很快反应，但录音提示音和开始录音的log要隔较久的时间才会播放出来，请问有没有什么改善策略？

我debug了一下，你直接进行play /home/pi/wukong-robot/static/beep_hi.wav 播放也是会有延时的，这应该是这段语音的问题，可以将语音重新截取一下。

**Comment by hanyanze** [comment]
> 您好，我在树莓派4B（装respeaker2麦克风阵列）上运行该程序时，在正确说出离线唤醒词后麦克风上的指示灯能很快反应，但录音提示音和开始录音的log要隔较久的时间才会播放出来，请问有没有什么改善策略？

我debug了一下，直接进行play /home/pi/wukong-robot/static/beep_hi.wav 播放也是会有延时的。目前还没有找到解决办法。
