### ISSUE TITLE
无法播放反回信息语音。

### ISSUE THREAD

**Issue by Vincentzpf** [wzpan/wukong-robot#113]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装/docker安装

**操作系统**

（例如 Raspbian Stretch、Ubuntu 16.04）

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

具体说明下问题

我已确保录音、播放都正常工作，机器人返回正常。但是系统无法播出返回的音频文件。
我使用命令可以播出音频。

![20200323152146](https://user-images.githubusercontent.com/44083704/77291892-12310080-6d1a-11ea-9d9a-9c1359c49852.png)

**Comment by wzpan** [comment]
问题可能为 alsa 与 pulseaudio 冲突导致。解决办法见：https://github.com/wzpan/wukong-robot/wiki/troubleshooting#%E8%AF%AD%E9%9F%B3%E5%8D%A1%E7%9D%80%E6%92%AD%E6%94%BE%E4%B8%8D%E5%87%BA%E6%9D%A5
