### ISSUE TITLE
报错，server_hostname cannot be an empty string or start with a leading dot.（已经找到解决办法，望源码也改进）

### ISSUE THREAD

**Issue by lmsccc** [wzpan/wukong-robot#119]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装/docker安装

**操作系统**

Raspbian Stretch

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

使用camera模块的时候，配置了拍照后发送到邮箱，报错
`server_hostname cannot be an empty string or start with a leading dot.`

**复现步骤**

拍照成功时，发送邮件会报错

**已找到解决办法**
在`utils.py`中，使用`smtplib.SMTP()`的时候，要传入`SMTP_SERVER`，即可解决问题，成功发送邮件

**Comment by wzpan** [comment]
done。2.2.2 版本多传了这个参数。
ps：我用 163 邮箱并没有这个问题啊。

**Comment by lmsccc** [comment]
我也是使用163邮箱，可能我们的python版本有所不同
