### ISSUE TITLE
默认查询天气逻辑可能有问题

### ISSUE THREAD

**Issue by ZhangJun1015** [wzpan/wukong-robot#12]
使用环境：Mac Mojove 10.14.2
问题描述：把心知天气 false ，唤醒孙悟空，提问【天气】，悟空回答【请问你想查询哪个城市？】，回答【深圳】，但之后没有任何反应了，也没有出现录制音频的提示音。

BTW：心知天气可以用了。

**Comment by wzpan** [comment]
那个是图灵的bug，有时候又可以
