### ISSUE TITLE
启动wukong后没有任何反应

### ISSUE THREAD

**Issue by kanglue** [wzpan/wukong-robot#121]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

docker安装

**操作系统**

Raspbian buster

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

具体说明下问题

pi@raspberrypi:~ $ docker run -it -p 5000:5000 --device /dev/snd -e LANG=C.UTF-8 wzpan/wukong-robot-arm:latest
root@19500e3f2fc8:~/wukong-robot# python3 wukong.py 
配置文件/root/.wukong/config.yml不存在，要创建吗？(y/n)y

********************************************************
*          wukong-robot - 中文语音对话机器人           *
*          (c) 2019 潘伟洲 <m@hahack.com>              *
*     https://github.com/wzpan/wukong-robot.git        *
********************************************************

            如需退出，可以按 Ctrl-4 组合键。

Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 924
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 924
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 924

程序卡在上面没有反应。
我用孙悟空无法唤醒程序
镜像系统中没有编辑器，不能编辑config.yml文件。
请指导，谢谢！

**Comment by wzpan** [comment]
这个不是卡，是你没能唤醒wukong-robot。参见 [使用技巧](https://wukong.hahack.com/#/tips?id=_1-%e6%8f%90%e5%8d%87%e5%94%a4%e9%86%92%e6%88%90%e5%8a%9f%e7%8e%87%e5%92%8c%e5%87%86%e7%a1%ae%e5%ba%a6) 了解如何提升唤醒成功率。
