### ISSUE TITLE
请问只要更换了唤醒词文件，不管文件名如何 即使直接替换wukong.pmdl 也无法启动

### ISSUE THREAD

**Issue by ffllc** [wzpan/wukong-robot#124]
root@6f9a4b4db571:~/wukong-robot# python3 wukong.py 

********************************************************
*          wukong-robot - 中文语音对话机器人           *
*          (c) 2019 潘伟洲 <m@hahack.com>              *
*     https://github.com/wzpan/wukong-robot.git        *
********************************************************

            如需退出，可以按 Ctrl-4 组合键。

ERROR (ClassifyModels():pipeline-detect.cc:713) PipelineDetect: undefined model type detected. Most likely you provided the wrong model.
terminate called after throwing an instance of 'std::runtime_error'
  what():  ERROR (ClassifyModels():pipeline-detect.cc:713) PipelineDetect: undefined model type detected. Most likely you provided the wrong model.

[stack trace: ]
Backtrace has not been implemented yet.

Aborted (core dumped)

**Comment by wzpan** [comment]
undefined model type detected. Most likely you provided the wrong model.

说明你的唤醒词不对，无法使用。

**Comment by ffllc** [comment]
> undefined model type detected. Most likely you provided the wrong model.
> 
> 说明你的唤醒词不对，无法使用。

您意思是我只能使用孙悟空这个唤醒词吗? 不能自定义一个?

**Comment by wzpan** [comment]
能自定义，不过我怀疑你训练得到的 pmdl 文件有问题。
