### ISSUE TITLE
请问我设置了使用腾讯的tts和asr, 为什么在使用过程中还是会调用百度tts  造成错误无法使用.

### ISSUE THREAD

**Issue by ffllc** [wzpan/wukong-robot#125]
我一开始使用百度的语音服务,特别不稳定,时不时就是Max retries exceeded with url.  使用的是我自己的百度账户也不行.
然后我换成了腾讯,但是还是会去调用百度造成错误.  
请问如何解决?
如下离职中,第一次成功, 第二次去调用百度失败,第三次成功,第四次又是调用百度造成失败.

INFO:__main__:开始录音
INFO:robot.Conversation:结束录音
INFO:robot.ASR:tencent-asr 语音识别到了：现在几点。
INFO:robot.AI:emotibot 回答：告诉你吧，是北京时间 11:52。你是不是早就知道了？
INFO:robot.TTS:tencent-tts 语音合成成功，合成路径：/tmp/tmpz2_yhttn.wav
INFO:snowboy:Keyword 1 detected at time: 2020-05-27 11:52:33
INFO:__main__:开始录音
INFO:robot.Conversation:结束录音
INFO:robot.ASR:tencent-asr 语音识别到了：明天星期几。
CRITICAL:robot.Conversation:HTTPConnectionPool(host='openapi.baidu.com', port=80): Max retries exceeded with url: /oauth/2.0/token?grant_type=client_credentials&client_id=w5v7gUV3iPGsGntcM84PtOOM&client_secret=KffXwW6E1alcGplcabcNs63Li6GvvnfL (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x97620050>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
INFO:snowboy:Keyword 1 detected at time: 2020-05-27 11:52:52
INFO:__main__:开始录音
INFO:robot.Conversation:结束录音
INFO:robot.ASR:tencent-asr 语音识别到了：明天星期几。
INFO:robot.AI:emotibot 回答：明天是5月28号，星期四。
INFO:robot.TTS:tencent-tts 语音合成成功，合成路径：/tmp/tmpidtds4bu.wav
INFO:snowboy:Keyword 1 detected at time: 2020-05-27 11:53:07
INFO:__main__:开始录音
INFO:robot.Conversation:结束录音
INFO:robot.ASR:tencent-asr 语音识别到了：嗯，后天的天气怎么样。
CRITICAL:robot.Conversation:HTTPConnectionPool(host='openapi.baidu.com', port=80): Max retries exceeded with url: /oauth/2.0/token?grant_type=client_credentials&client_id=w5v7gUV3iPGsGntcM84PtOOM&client_secret=KffXwW6E1alcGplcabcNs63Li6GvvnfL (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x97620810>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

**Comment by ffllc** [comment]
client_id  client_secret 也不是我设置进去的

**Comment by ffllc** [comment]
在Brain 里面找到了这个key
args = {
            "service_id": "S13442",
            "api_key": 'w5v7gUV3iPGsGntcM84PtOOM',
            "secret_key": 'KffXwW6E1alcGplcabcNs63Li6GvvnfL'
        }
是不是由于使用的人太多 被百度临时中断了?

**Comment by wzpan** [comment]
嗯，是百度UNIT被限频了……我得考虑去中心化了

**Comment by ffllc** [comment]
snowboy也被百度搜狗了.  我估计unit交钱能解决. 但是这项目毕竟不是商业项目 也是尴尬.

**Comment by wzpan** [comment]
@ffllc 2.3.0 已经支持使用自己的UNIT账号了。可以解决QPS限频问题：https://github.com/wzpan/wukong-robot/wiki/update-notes#230
