### ISSUE TITLE
可以支持若琪rokid月石音箱吗？

### ISSUE THREAD

**Issue by fyanjin** [wzpan/wukong-robot#128]
手上有若琪月石音箱，硬件配置和使用感受都还不错，可惜的是听说这家公司放弃了音箱业务，而且相关服务器也会关闭，所以想到能否给若琪刷机成悟空系统的，如果可以的话那就太棒了，如果既可以刷机又有相关的教程，那就相当棒了。

**Comment by wzpan** [comment]
没试过，但是 Rokid 似乎是有提供 Linux 版本的固件，而 wukong-robot 支持运行在 Linux 系统中，所以在上面安装 wukong-robot 有可能是可行的。

**Comment by fyanjin** [comment]
非常感谢，看来是有办法的，只是自己水平有限，期待能有大神对此感兴趣，可以提供指导。
