### ISSUE TITLE
希望增加TTS的API

### ISSUE THREAD

**Issue by sirarikako** [wzpan/wukong-robot#129]
看了下API的介绍，基本都是基于管理的API。
在使用智能家居中，会有很多需要语音播报部分的处理。
现在是把悟空放在一个屋子里当作智能音箱来使用，所以希望能够支持TTS的API。

谢谢

**Comment by wzpan** [comment]
可以使用 echo 插件：https://wukong.hahack.com/#/official?id=echo

**Comment by sirarikako** [comment]
好的，谢谢~~~
