### ISSUE TITLE
后台网页无法回复任何问题

### ISSUE THREAD

**Issue by cyicz123** [wzpan/wukong-robot#133]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装

**操作系统**

Raspbian Stretch

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**
对于后台网页的交互完全无法回答。即使提问“你是谁”这种简单问题。
日志输出：

Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 924
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 924
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 934
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 934
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 934

第二次想复现问题甚至无法打开后台网页。

**Comment by cyicz123** [comment]
我还想问如果想重新安装，卸载的时候有什么要注意的吗？

**Comment by wzpan** [comment]
1. 用的什么对话机器人的API？
2. 没有。

**Comment by cyicz123** [comment]
> * 用的什么对话机器人的API？
> * 没有。

我是直接跟着文档手动安装的。安装完后由于没有麦克风想直接通过后台来测试是否安装成功。
我不太清楚用的什么API。

**Comment by wzpan** [comment]
wukong-robot 默认使用图灵对话机器人的API，而提供给大家试用的账号一天只有500次调用次数。所以一下子就被其他人用完了。用完就会无法对话。
你需要自己去申请对话机器人、TTS、ASR 的账号，才能正常使用wukong-robot。详见：https://github.com/wzpan/wukong-robot/blob/master/static/default.yml

**Comment by cyicz123** [comment]
好的 十分感谢
