### ISSUE TITLE
wukong-robot里怎么添加语音控制舵机运行

### ISSUE THREAD

**Issue by ppsu** [wzpan/wukong-robot#134]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装/docker安装

**操作系统**

（例如 Raspbian Stretch、Ubuntu 16.04）

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

具体说明下问题
想在wukong-robot里怎么添加语音控制舵机操作，不知道怎么添加

**Comment by wzpan** [comment]
没玩过舵机，但是也许可以有两个方案：
- 方案1：C/S 模式
  1. 搭建一个舵机控制的 web 服务，例如如果你是用 ROS 的话，可以用 [ROStful](https://www.ros.org/news/2014/02/introducing-rostful-ros-over-restful-web-services.html)。
  2. 编写 wukong-robot 插件，调用上面的 restful 接口。
  好处是不用跟 wukong-robot 耦合太多，架构比较轻量化。缺点是调用可能会慢一点。
- 方案2：直接控制舵机
  直接写 wukong-robot 的插件，驱动 ROS 。比如用 [RosPy](http://wiki.ros.org/rospy) ，或者直接混编 C++ 。
