### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by qq2398658355** [wzpan/wukong-robot#136]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装/docker安装

**操作系统**

（例如 Raspbian Stretch、Ubuntu 16.04）

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

具体说明下问题

修改condig.yml里" first_name:师父 " 的"师父"成其他词后启动报错，修改回来就可以正常运行了，求解，谢谢
报错如下

Traceback (most recent call last):
  File "wukong.py", line 273, in <module>
    wukong.run()
  File "wukong.py", line 116, in run
    self.init()
  File "wukong.py", line 49, in init
    self._conversation.say('{} 你好！试试对我喊唤醒词叫醒我吧'.format(config.get('first_name', '主人')), True)
  File "/home/pi/wukong/robot/Conversation.py", line 205, in say
    self.player.play(voice, not cache, onCompleted, wait)
  File "/home/pi/wukong/robot/Player.py", line 84, in play
    if os.path.exists(src) or src.startswith('http'):
  File "/usr/lib/python3.7/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by wzpan** [comment]
`firstname: 师父` 里的这个 `:` 和后面的内容需要保留一个空格，检查一下。

**Comment by qq2398658355** [comment]
已解决，多谢
