### ISSUE TITLE
能否用seeed respeaker 4mics的led灯 

### ISSUE THREAD

**Issue by ly4661870** [wzpan/wukong-robot#137]
没有找到相关关联

**Comment by wzpan** [comment]
目前是没有支持 4mics 的灯（因为我没有硬件）。但是 4mics 和 2mics 的驱动很类似，你可以参考 2mics 的方式做一些适配。大概就是把 [Pixel](https://github.com/wzpan/wukong-robot/blob/master/robot/drivers/pixels.py) 的脚本换成 4mics 的应该就可以了。
