### ISSUE TITLE
snowboy停止API服务了

### ISSUE THREAD

**Issue by sunhanaix** [wzpan/wukong-robot#139]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装

**操作系统**

 Raspbian 3B+

**离线唤醒相关**

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

snowboy官网的api已经shutdown了，
wukong.py里面写死的https://snowboy.kitt.ai/api/v1/train/这个要重新考虑下具体实现了。

**复现步骤**
https://github.com/Kitt-AI/snowboy/
The field of artificial intelligence is moving rapidly. As much as we like our products, we still see that they are getting outdated and are becoming difficult to maintain. All official websites/APIs for our products will be taken down by Dec. 31st, 2020. Our github repositories will remain open, but only community support will be available from this point beyond.

**Comment by wzpan** [comment]
您好，建议尝试自行部署一个snowboy的训练服务。详见：https://github.com/rhasspy/snowboy-seasalt

**Comment by wzpan** [comment]
已提供snowboy训练服务：https://snowboy.hahack.com/

**Comment by wzpan** [comment]
久无回复，先关闭了。如果有问题可继续提问。

**Comment by ifzm** [comment]
@wzpan 训练服务打不开了

**Comment by wzpan** [comment]
@ifzm 已恢复

**Comment by ifzm** [comment]
@wzpan Thanks ）

**Comment by duriancashewTasty** [comment]
@wzpan  您好，这个snowboy训练服务：https://snowboy.hahack.com/  是否对于中文敏感，使用中文尝试之后，没有准确识别到。另外在safari浏览器中打开录音之后，显示错误音频。在谷歌上正常，生成的pmdl，在snowboy中没有识别到。换回官方的唤醒词文件可以识别。

**Comment by wzpan** [comment]
@duriancashewTasty 这个服务来自于 https://github.com/rhasspy/snowboy-seasalt ，未做改动。
