### ISSUE TITLE
遇到docker: unknown server OS: .错误，加sudo无效

### ISSUE THREAD

**Issue by astroxyx** [wzpan/wukong-robot#143]
你好，我想在树莓派4B上安装悟空，但是执行到
`docker run -it -p 5000:5000 --device /dev/snd -e LANG=C.UTF-8 wzpan/wukong-robot-arm:latest`
的时候，提示docker: unknown server OS: .，我尝试过加sudo，结果也一样。
是不是docker上的wukong-robot-arm还不支持树莓派4B呀？
![image](https://user-images.githubusercontent.com/43833930/114643225-d5aabb00-9d07-11eb-9729-51fbbf51a636.png)

**Comment by wzpan** [comment]
应该和 wukong-robot-arm 镜像无关，看看是否能运行其他镜像，比如 `docker run hello-world` 。

如果不能，试试这篇文章的指导，让你的普通用户也能跑docker看看：https://docs.docker.com/engine/install/linux-postinstall/

配置完后再试试 `docker run hello-world` ，如果此时可以，再运行 wukong-robot-arm 。

**Comment by astroxyx** [comment]
谢谢你，我切换到超级目录下运行就可以了，在普通用户下加了sudo也没用。
