### ISSUE TITLE
如何在本地比较方便的debug开发的插件？

### ISSUE THREAD

**Issue by laozhuang727** [wzpan/wukong-robot#145]
比如我们要测试Weather的插件，发现调用失败，我们要比较方便的去定位到底哪里出了问题，请问比较好的方式是什么？

个人临时做了一个取巧的动作，就是把插件代码，copy一份到wukong-robot/plugins 下面，然后添加main方法进行处理，不过有点恶心，请问正确的做法应该怎么办？

if __name__ == '__main__':

    c = Conversation()
    wealth = Plugin(con=c)

    args = {
        "service_id": config.get('/unit/service_id', 'S13442'),
        "api_key": config.get('/unit/api_key', 'w5v7gUV3iPGsGntcM84PtOOM'),
        "secret_key": config.get('/unit/secret_key', 'KffXwW6E1alcGplcabcNs63Li6GvvnfL')
    }
    parsed = c.doParse("上海天气怎么样", **args)

    wealth.handle("上海天气怎么样", parsed)

**Comment by wzpan** [comment]
`$HOME/.wukong/custom` 目录的就是用于本地调试的，无需发布。建议先认真阅读 [实战篇1：hello world](https://wukong.hahack.com/#/writing-skill-1)

**Comment by wzpan** [comment]
久无回复，先关闭了。如果有问题可继续提问。
