### ISSUE TITLE
无法唤醒 

### ISSUE THREAD

**Issue by sitchain** [wzpan/wukong-robot#150]
启动程序后 通过后台录音正常 但无法播放 无法唤醒

**Comment by wzpan** [comment]
你这个issue信息太简单，无法分析。请补充完整信息。

1. 无法播放：

是播的过程卡住呢，还是播放没声音呢？

2. 无法唤醒：

是否已确保 arecord temp.wav、aplay temp.wav (Linux) 或 rec temp.wav、play temp.wav （Mac）已正常工作？
