### ISSUE TITLE
能否增加微软TTS接口？微软的晓晓的语音超级惊艳

### ISSUE THREAD

**Issue by libingtong** [wzpan/wukong-robot#153]
能否增加微软TTS接口？微软的晓晓的语音超级惊艳
https://azure.microsoft.com/zh-cn/services/cognitive-services/text-to-speech/#features

**Comment by wzpan** [comment]
Ok，我近期接一下

**Comment by libingtong** [comment]
> Ok，我近期接一下

微软的tts neural目前好像只支持东南亚和美国地区，申请会稍微麻烦一些，需要信用卡。如果需要可以发邮件给我，我提供我申请的试用Key给您测试。tts@7626.net

**Comment by wzpan** [comment]
@libingtong 如果是这样的话，那这个支持不太适合。因为wukong-robot主要是面向大陆地区的用户，过于小众的需求建议大家自行扩展实现。

**Comment by jack9603301** [comment]
@wzpan 慢慢的向国际社区过度不好嘛？就如HASS一样，支持几乎所有的组件

**Comment by jack9603301** [comment]
> > Ok，我近期接一下
> 
> 微软的tts neural目前好像只支持东南亚和美国地区，申请会稍微麻烦一些，需要信用卡。如果需要可以发邮件给我，我提供我申请的试用Key给您测试。[tts@7626.net](mailto:tts@7626.net)

诶，那你是怎么申请到的？

**Comment by wzpan** [comment]
@jack9603301 ROI 有点低。先满足好国内用户吧。欢迎大家 PR 。

**Comment by jack9603301** [comment]
> @jack9603301 ROI 有点低。先满足好国内用户吧。欢迎大家 PR 。

不过现在可以开始慢慢推进了，比如说注释更多的使用英文，减少中文，还有提交信息也是，文档提供双语支持等等

**Comment by libingtong** [comment]
> > > Ok，我近期接一下
> > 
> > 
> > 微软的tts neural目前好像只支持东南亚和美国地区，申请会稍微麻烦一些，需要信用卡。如果需要可以发邮件给我，我提供我申请的试用Key给您测试。[tts@7626.net](mailto:tts@7626.net)
> 
> 诶，那你是怎么申请到的？如果是这样，我建议你自行实现然后提交PR

申请没任何难度，就是国际版的Azure，仅仅是需要信用卡，稍微有点麻烦而已。

**Comment by jack9603301** [comment]
> > > > Ok，我近期接一下
> > > 
> > > 
> > > 微软的tts neural目前好像只支持东南亚和美国地区，申请会稍微麻烦一些，需要信用卡。如果需要可以发邮件给我，我提供我申请的试用Key给您测试。[tts@7626.net](mailto:tts@7626.net)
> > 
> > 
> > 诶，那你是怎么申请到的？如果是这样，我建议你自行实现然后提交PR
> 
> 申请没任何难度，就是国际版的Azure，仅仅是需要信用卡，稍微有点麻烦而已。

哪里可以考虑提交PR

**Comment by guoxiangke** [comment]
建议还是增加这个吧，不喜欢用国内的服务。
还有一个 api.ai 服务 的被google 收购了，改名： https://dialogflow.cloud.google.com 
希望能支持
