### ISSUE TITLE
关于自定义语音识别和语音合成？

### ISSUE THREAD

**Issue by icenaive** [wzpan/wukong-robot#158]
请问可以不使用百度腾讯等语音识别的API，然后调用本地的语音识别模型吗？

**Comment by wzpan** [comment]
wukong-robot集成了一个本地TTS服务[HanTTS](https://wukong.hahack.com/#/install?id=hantts-%e5%ae%89%e8%a3%85%ef%bc%88%e5%8f%af%e9%80%89%ef%bc%89)。

但无论是 TTS 和 ASR ，目前尚没有一个达到工业级别可用的中文开源本地化方案。
