### ISSUE TITLE
播放音质

### ISSUE THREAD

**Issue by c-box** [wzpan/wukong-robot#160]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装/docker安装

**操作系统**

（例如 Raspbian Stretch、Ubuntu 16.04）

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

具体说明下问题

播放本地音乐或者录音时，声音断断续续，音质较差，和用其他播放器播放的声音相差甚远，请问是什么原因导致的？

**Comment by wzpan** [comment]
是用了蓝牙音箱还是普通外放？直接用 `play` 命令播放一些 mp3 文件会卡不？

**Comment by c-box** [comment]
> 是用了蓝牙音箱还是普通外放？直接用 `play` 命令播放一些 mp3 文件会卡不？

普通外放，直接在终端play是正常的，但是调用项目里的API就会出问题

**Comment by c-box** [comment]
> 是用了蓝牙音箱还是普通外放？直接用 `play` 命令播放一些 mp3 文件会卡不？

我包括直接在python里使用subprocess.Popen(cmd)，cmd为对应的播放命令，声音也是正常的，只有在wukong的项目里调用这个的时候才会卡顿，而且非常明显，您觉得有什么可能的原因吗？

**Comment by wzpan** [comment]
是实际上 LocalPlayer 也是用的 play 命令。没想到有啥原因。看看运行时候内存，CPU 的占用率？

**Comment by c-box** [comment]
> 实际上 LocalPlayer 也是用的 play 命令。没想到有啥原因。看看运行时候内存，CPU 的占用率？

换成了mplayer是正常的
