### ISSUE TITLE
报错：Errno -9996 Invalid input device (no default output device)

### ISSUE THREAD

**Issue by wangwei921216** [wzpan/wukong-robot#163]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装/docker安装

**操作系统**

（例如 Raspbian Stretch、Ubuntu 16.04）

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

已配置好麦克风 和 音响！
运行 python3 wukong.py 时报错 
shared memfd open() failed: Function not implemented
shared memfd open() failed: Function not implemented
shared memfd open() failed: Function not implemented
CRITICAL:__main__:离线唤醒机制初始化失败：Errno -9996 Invalid input device (no default output device)

**Comment by zhangyuhanzyh** [comment]
重新启动或许可以

**Comment by palorisisis** [comment]
我也遇到这个问题，但是没有解决方案

**Comment by palorisisis** [comment]
Expression 'paInvalidSampleRate' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2048
Expression 'PaAlsaStreamComponent_InitialConfigure( &self->capture, inParams, self->primeBuffers, hwParamsCapture, &realSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2719
Expression 'PaAlsaStream_Configure( stream, inputParameters, outputParameters, sampleRate, framesPerBuffer, &inputLatency, &outputLatency, &hostBufferSizeMode )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2843
CRITICAL:__main__:离线唤醒机制初始化失败：[Errno Invalid sample rate] -9997

**Comment by wzpan** [comment]
<img width="784" alt="image" src="https://user-images.githubusercontent.com/1631405/163354076-878bfcf4-a518-47ff-85f2-d4569b24d6d9.png">
-9996 已经有很多其他地方询问过了，先看看历史issue。

**Comment by shenxueyuan** [comment]
我树莓派开机默认启动，也碰到了这个问题，解决办法是，在启动的之前，先sleep 20 。然后就没问题了。应该是系统、硬件没初始化好，立刻启动就会碰到这个问题。
