### ISSUE TITLE
说话总是识别错误或识别不了

### ISSUE THREAD

**Issue by ChenYugen** [wzpan/wukong-robot#168]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装/docker安装

**操作系统**

Ubuntu 14.04（虚拟机）

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

具体说明下问题
使用arecord temp.wav`、`aplay temp.wav` (Linux)  都正常。
但是在后台界面使用录音时，总是识别不到或者识别错了。

INFO:robot.ASR:baidu-asr 语音识别出错了: speech quality error.
INFO:robot.TTS:baidu-tts 语音合成成功，合成路径：/tmp/tmpuv792h8z.mp3
INFO:robot.Conversation:False
INFO:robot.Conversation:onSay: 没听清呢, http://0.0.0.0:5000/audio/935ac469e160c37ef3ad5370cb5c0132.mp3

找到/tmp/tmpuv792h8z.mp3的文件，发现全是杂音。

**Comment by wzpan** [comment]
```
speech quality error
```

说明你的录音质量有问题，考虑换个录音设备。

**Comment by ChenYugen** [comment]
啊，这样啊。但是我用arecord录的声音没有问题。。我换一个试试先
