### ISSUE TITLE
锤子科技智能音箱David& Sheryl D1刷机

### ISSUE THREAD

**Issue by dukoalad** [wzpan/wukong-robot#169]
锤子科技的这款音箱David& Sheryl D1发布会开了，但是产品没有上市就...
现在手中的是工程机，目前能连蓝牙使用
手中有一台工程样机，因为服务器也断了，无法配网，

**求配网指导或者刷机指导**（斐
讯黄了后，还有教程能激活其设备）。
目前仅能当作蓝牙音箱使用。

1.机身顶部有5个按键（音量＋、音量-、后退、快进、播放）
2.机身一个静音键（测试发现长按退出配网模式，短按3s
讲入配网模式）
3.底部—个DC电源接口、
一个AUX接口；
4.贴有SN码、Mac地址。

**Comment by FranzeBK** [comment]
我也有个这个工程机，请问这个有什么简单方法改一下直接当蓝牙音箱用么？

**Comment by dukoalad** [comment]
本身就支持蓝牙音箱功能呀
