### ISSUE TITLE
请问如何训练格式为umdl的通用唤醒词~谢谢~

### ISSUE THREAD

**Issue by 805094591** [wzpan/wukong-robot#173]
请问如何训练格式为umdl的通用唤醒词
有哪些源代码，网站或其他参考资料
谢谢

**Comment by 805094591** [comment]
谢谢。
您好。这个页面（https://github.com/seasalt-ai/snowboy）所展示的“Snowboy Hotword Detection/Alexa support/Universal model”栏目提到了格式为umdl的通用唤醒词，请问如果使用这种方法是否能够训练格式为umdl的通用唤醒词。谢谢。
![a1](https://user-images.githubusercontent.com/39234160/162613445-e11f6fd4-958a-46bf-ad24-246dc28e932e.png)

**Comment by wzpan** [comment]
你仔细看看内容，这里说的是umdl的用法，而不是训练方法。
目前能下载到的现成的 umdl 在这里：https://github.com/Kitt-AI/snowboy/tree/master/resources/models
但是已经没办法训练新的。另外 umdl 需要至少上千个不同人的样本参与训练，如果是个人，是无法独立完成 umdl 训练的。

**Comment by 805094591** [comment]
好的~明白了~非常感谢~辛苦您了~
