### ISSUE TITLE
 Max retries exceeded with url百度语音合成出现问题

### ISSUE THREAD

**Issue by ozil111111** [wzpan/wukong-robot#174]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装/docker安装

**操作系统**

（例如 Raspbian Stretch、Ubuntu 16.04）

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

具体说明下问题
INFO:__main__:开始录音
INFO:robot.Conversation:结束录音
CRITICAL:robot.Conversation:HTTPSConnectionPool(host='aip.baidubce.com', port=443): Max retries exceeded with url: /oauth/2.0/token?grant_type=client_credentials&client_id=ikpgpWl8IAFmlTQWAzeZkusS&client_secret=vf1VQ6a70hsbfqdjVUS8h6E2m15eM97G (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x57cd3030>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

API和秘钥是我自己两周前创建的，以前调用都能正常运作，突然出现这个问题，查了以前的issue，提到是限频问题，请问怎么解决？

**Comment by wzpan** [comment]
网络问题。检查一下你的网络环境以及hosts文件吧。
