### ISSUE TITLE
就是一个壳? TTS 语音识别都是线上的?这是Robot? 还是云上服务?

### ISSUE THREAD

**Issue by snowyu** [wzpan/wukong-robot#176]
Intent Recognition 是不是也是线上的? 还是全是调用服务?

本地TTS一大堆, 本地语音识别也是大堆, 不明白为傻线上,可以背后人工服务,显得机器人能像人?

**Comment by wzpan** [comment]
wukong-robot 本身就是一个积木式的机器人框架，开发者可以自己挑选自己喜欢的模块搭建一套机器人。
追求速度就用离线的接口，Intent Recognition也是松耦合的，可以自己hack。
也见过有人继承AbstractASR实现自己的一套ASR。
当然如果你感兴趣，背后搞个人工服务显得机器人像人也是可以的，这是我开仓库以来见过的脑洞最大的一个issue。加油。
