### ISSUE TITLE
能不能改变成Android客户端+服务器模式

### ISSUE THREAD

**Issue by zhidd** [wzpan/wukong-robot#177]
当前代码改变成服务器端，Android端负责语音识别成文字，然后发送给服务器，服务器返回语音

**Comment by wzpan** [comment]
wukong-robot本身就是开放API的，只需要再写一个Android client即可。
另外也可以试试结合qq频道机器人的客户端：https://github.com/wzpan/wukong-qq-guild
演示demo：https://www.bilibili.com/video/BV1144y1P7tB?spm_id_from=333.999.0.0

**Comment by wzpan** [comment]
已经给出了方案，本issue关闭。
