### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by ghost** [wzpan/wukong-robot#179]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**
一键脚本安装

**操作系统**
优麒麟操作系统

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

具体说明下问题

出现以下问题

module 'collections' has no attribute 'MutableSet'

**Comment by wzpan** [comment]
看着是 Python 3.10 的特定问题哈。https://blog.csdn.net/lishuaigell/article/details/125221750

**Comment by RizhaoCai** [comment]
换到Python3.9可以解决

**Comment by zwssunny** [comment]
应该升级一下包  pip install watchdog -U
