### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by q872839000** [wzpan/wukong-robot#182]
root@DESKTOP-MRQLURS:/home/pcy/wukong-robot# python3 wukong.py
/usr/local/lib/python3.8/dist-packages/pydub/utils.py:165: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)

********************************************************
*          wukong-robot - 中文语音对话机器人           *
*          (c) 2019 潘伟洲 <m@hahack.com>              *
*     https://github.com/wzpan/wukong-robot.git        *
********************************************************

            后台管理端：http://0.0.0.0:5000
            如需退出，可以按 Ctrl-4 组合键

Traceback (most recent call last):
  File "wukong.py", line 299, in <module>
    wukong.run()
  File "wukong.py", line 131, in run
    self.init()
  File "wukong.py", line 56, in init
    self._conversation.say(
  File "/home/pcy/wukong-robot/robot/Conversation.py", line 237, in say
    self.player.play(voice, not cache, onCompleted, wait)
  File "/home/pcy/wukong-robot/robot/Player.py", line 91, in play
    if os.path.exists(src) or src.startswith("http"):
  File "/usr/lib/python3.8/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
root@DESKTOP-MRQLURS:/home/pcy/wukong-robot#

**Comment by wzpan** [comment]
是否有更新到最新版本呢？
