### ISSUE TITLE
如何训练一个通用模型来更改唤醒词？个人模型给其他人来唤醒效果较差。

### ISSUE THREAD

**Issue by glk-hll** [wzpan/wukong-robot#184]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装

**操作系统**

Mac Os

**离线唤醒相关**
—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

具体说明下问题

**Comment by wzpan** [comment]
snowboy 已经没有提供训练 umdl 的平台了。

**Comment by glk-hll** [comment]
哦哦哦 感谢回答！那是不是只能通过训练个人模型或者选择文档中提到的预训练通用模型来离线唤醒？还有一个问题，这些预训练通用模型的唤醒词是不是模型文件名？

**Comment by wzpan** [comment]
> 那是不是只能通过训练个人模型或者选择文档中提到的预训练通用模型来离线唤醒？
是的

> 还有一个问题，这些预训练通用模型的唤醒词是不是模型文件名？
是的

**Comment by glk-hll** [comment]
明白了，謝謝。
