### ISSUE TITLE
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

### ISSUE THREAD

**Issue by yuib3** [wzpan/wukong-robot#187]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装

**操作系统**

armbian 22.08.2 

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

具体说明下问题
大佬好，我使用的是orangpi zero puls2 H3（香橙派）的板子，环境是python3.10，安装过程中修改了  MutableMapping属性添加了adc，因为好像Python3.10的这个有模块有所改动，然后我安装watchdog模块因为仓库里的版本（0.9.0 ）安装不上就安装的1.0.0版本的，因为是在校学生比较菜，不知道是不是我的改动有问题所以在这里提一下，在服务器上实验过了回复语音这些没有问题

问题：
运行界面提示CRITICAL:__main__:离线唤醒机制初始化失败：
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

**Comment by wzpan** [comment]
https://stackoverflow.com/questions/70705404/systemerror-py-ssize-t-clean-macro-must-be-defined-for-formats
似乎是 Python 3.10 引入的 breaking changes 导致。
使用这个 fork 版本的 PyAudio 也许可以解决问题：https://git.skeh.site/skeh/pyaudio

**Comment by yuib3** [comment]
> 

好的，谢谢大佬，我后面有空试一下，现在疫情封控了东西没在身边
