### ISSUE TITLE
请问如何关闭读拍照的URL，又不影响会话里照片的显示。

### ISSUE THREAD

**Issue by prairiewolf12** [wzpan/wukong-robot#189]
**确认已寻找过答案**
我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。
**安装方式**
手动安装
**操作系统**（Raspbian）
—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

唤醒后说"拍照"，拍完照悟空机器人就会说出照片的URL，非常长，念一长串数字出来，貌似没啥用，一般人都不会听着把URL输入浏览器里打开。所以我想关闭读出URL的部分。
self.say("拍照成功：{}".format(photo_url), cache=True)
改成self.say("拍照成功", cache=True)
改掉这句后，虽然能拍照，但会话里又不显示照片了。简单说：要实现拍照，不读URL，还能显示照片。

wukong.hahack.com里有“悄悄拍照”的功能，但这样又没有在会话窗里显示照片。

**Comment by wzpan** [comment]
请更新到最新的 3.1.0 版本，解决了这个问题。

**Comment by prairiewolf12** [comment]
感谢感谢。大神写的OpenAI比我的好太多了，我也把我的OpenAI换下来了。
