### ISSUE TITLE
读OpenAI回答代码的bug

### ISSUE THREAD

**Issue by prairiewolf12** [wzpan/wukong-robot#192]
**确认已寻找过答案**

前天版本升级中新增的OpenAI，引入了一个新Bug。
在会话中发送“图片”，回复中大量代码，如下：
![bug](https://user-images.githubusercontent.com/124415166/218452063-de60552d-1159-460c-b5d4-76378d67f2e5.png)
回答是没问题，只是say函数会读一遍就难过了。
发送其他的，openai也可能会回答代码，没必要读出来了。还希望大神出马。

**Comment by wzpan** [comment]
实际上你这个返回里的内容只是 GPT 返回的纯文本信息，而从纯文本的角度上是无法准确识别出里头是不是代码的。

除非 GPT 返回的代码中统一都加了 ``` 作为返回字符串，这种比较好处理一点。否则，除非目前已经有成熟的判断一段纯文本里是否有代码的 NLP 算法，否则不太可行。

因为 GPT 返回的内容通常很长一大段，所以实际上这个朗读也不会全都读——超出100个字符后我默认就会让 wukong-robot 结束不读。

**Comment by wzpan** [comment]
> 人说话很少说大量符号，是否可以统计里面的+－*/ " '这类的符号，超过一定的量就判定为代码？

这个规则过于不通用了。有+-*/并不能说明就是代码。

**Comment by prairiewolf12** [comment]
好的，感谢感谢。

**Comment by jack9603301** [comment]
我认为可能是解析错误。并且代码通常具备特定的语法格式，可以被特定语言的通用语法解析器解析，能被正确解析的则判定为代码，这可以通过机器学习来完成

**Comment by wzpan** [comment]
anyway，3.1.2做了个代码格式的优化，现在可以正常支持折行，展示代码段。

![3b20ad31ca7038d8411bf761f3b7ab0e](https://user-images.githubusercontent.com/1631405/220250227-87ba64d0-4128-41e8-a6e6-4f303894c69d.jpeg)
