### ISSUE TITLE
配置聊天机器人为openai后，网络连接失败

### ISSUE THREAD

**Issue by qcoltma** [wzpan/wukong-robot#197]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装/docker安装

**操作系统**

（例如 Raspbian Stretch、Ubuntu 16.04）

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

具体说明下问题
建议在配置文件中增加代理服务器的配置。

**Comment by wzpan** [comment]
openai 的服务已经被墙，你需要科学上网才能正常使用这个服务。

**Comment by qcoltma** [comment]
> openai 的服务已经被墙，你需要科学上网才能正常使用这个服务。

我已经科学上网了，用的是代理，就是wukongrobot没有设置代理的地方，建议有配置文件中有proxy=****:***的配置。

**Comment by wzpan** [comment]
可以用 proxychains 来启动 wukong 实现代理

**Comment by prairiewolf11** [comment]
语音识别与合成都是国内的，openai是国外的，怕是容易暴露吧。为openai单独走个代理通道才放心。

**Comment by qcoltma** [comment]
> 可以用 proxychains 来启动 wukong 实现代理

想让语音识别啥的都走国内，仅openai走代理，这样响应速度不会太慢。

**Comment by wzpan** [comment]
@prairiewolf11 @qcoltma wukong-robot 3.3.0 已发布。可以更新到这个版本，增加了 OpenAI 代理的支持。详见：https://github.com/wzpan/wukong-robot/wiki/update-notes#330
