### ISSUE TITLE
加速合成的一点小思路，长语句，按 ， 。 ！ 进行分割，在读第一句的时候，利用这个时间合成下一句。

### ISSUE THREAD

**Issue by prairiewolf11** [wzpan/wukong-robot#208]
**确认已寻找过答案**

**问题描述**
加速合成的一点小思路，“分段合成”。长语句，按 ， ； 。 ！  进行分割，在读第一句的时候，利用这个时间合成下一句。
优点：加快了反应速度。
缺点：消耗更多的API调用量。

可以加一个参数，由用户根据自己的情况，是否启用“分段合成”功能。

**Comment by wzpan** [comment]
谢谢你的建议，这是一个非常好的想法。只是目前 wukong 的 Player 默认是非阻塞的，所以当我拆分句子后得小心做好 onCompleted 的衔接，否则就会出现一堆句子同时播放的问题。

要解决这个问题，我需要把 Player 的播放机制从单任务做成一个队列，顺便干掉 wait 参数。这样才能简单而优雅的实现你的想法。

我近期会考虑对 Player 做个重构支持这个 feature 。

**Comment by wzpan** [comment]
需要先实现好 Player 的子线程播放队列，才能考虑做这个 feature 。否则要么在播放声音过程中无法唤醒（阻塞了主线程），要么就会很容易出现多段语音同时播放的问题（不阻塞，但是异步同时叠加播放了音频）。

**Comment by prairiewolf11** [comment]
优化一下我最早的思路：
为减少多次合成造成的API的调用量大增的缺点，可以把长内容拆分成2段，第1段只有1句，播放这句的时间内，把剩下的第2段也完成合成并下载下来。然后再播放第2段。这样的合成，只调用了2次API。（大致思路）

详细思路：
如果要更精细的控制，可以计算合成第一句并下载所用的时间t1,再计算播放这句所用的时间t2，用t1(包含API调用速度与网络速度有关的不可控因素)预估剩下的内容合成并下载所用的时间t3,如果t2-t3>0,拆分成2段就没问题；如果t2-t3<0，说明播放第一句的时间不够剩下的内容合成，所以剩下的内容还要拆分；重复执行，直到最后一段内容的时间小于前一句的播放时间，就结束拆分。另外，还应该考虑一点提前量，以应对网络波动。

**Comment by wzpan** [comment]
不需要这么复杂，我的想法是全部句子丢线程池里消化。文本生产者-TTS 消费者/播放队列生产者-播放队列消费者的方式。

**Comment by wzpan** [comment]
[3.4.0版本](https://github.com/wzpan/wukong-robot/discussions/215) 已实现了多线程TTS加速合成的能力。

**Comment by prairiewolf11** [comment]
大神辛苦了，感谢能百忙之中更新软件。
从版本3.4.0的日志看，貌似是先一个个的合成，都合完了，再一个个播放的。截图里，第一句话的语音晚播放了0.5秒，应该在18:38:41,851播放才对，读取音频文件大概需要0.003秒的样子。
是不是应该是把播放的优先级提到最高，只要是按顺序合成完就立刻播放。
比如有4句话，都送到线程池里去合成，然后有一个线程等第1句的合成结果，只要第1句合成成功就立刻播放，然后等第2句……
![日志](https://user-images.githubusercontent.com/8274686/227771079-74cee890-8969-43de-b4a5-27a8654f9df8.png)

**Comment by wzpan** [comment]
做是可以做，不过代码可能就会写的很难看。
这个等我后面再看看。

**Comment by wzpan** [comment]
优化了一把。这次一旦合成 TTS ，会立马按顺序进入播放，而不会等到所有 TTS 合成完成。

**Comment by prairiewolf11** [comment]
牛。

**Comment by prairiewolf11** [comment]
我统计了一下，合成一句话用时大约是0.4+秒，播放一句话大约是6秒。所以在播放第1句话的时候，剩下的所有内容均已合成成功。
说明：所有内容拆分成2段就足够。这样能节省API调用量。至少能省一半。
