### ISSUE TITLE
mac下使用麦克风无法唤醒，使用耳机可以唤醒

### ISSUE THREAD

**Issue by liunaijie** [wzpan/wukong-robot#21]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装/docker安装

**操作系统**

（例如 Raspbian Stretch、Ubuntu 16.04）

**问题描述**

具体说明下问题

**Comment by wzpan** [comment]
请先完善下说明。安装方式是手动安装还是docker安装？问题描述是啥？

**Comment by liunaijie** [comment]
不好意思，点了一下回车没填写描述就直接提交了。。
我是手动安装，在macmini上使用耳机可以正常唤醒，但是使用麦克风却无法唤醒

**Comment by wzpan** [comment]
我在 Mac 下也是手动安装，但没有这个问题。

你用自带麦克风能够正常 rec 和 play 吗？自测一下这两个能正常再尝试使用 wukong-robot 。

``` sh
rec test.wav 
```

随便说点东西，然后：

``` sh
play test.wav
```

看看能不能播放。

**Comment by liunaijie** [comment]
好的，十分感谢
