### ISSUE TITLE
可以增加一个获取准确度高的空气质量插件吗？

### ISSUE THREAD

**Issue by prairiewolf11** [wzpan/wukong-robot#211]
国内的空气质量都不准确，美国大使馆https://aqicn.org/city/ 这个网站的空气质量数据精度相当高，但因为太准确而被墙了。
可以用走代理的形式做一个插件吗？就像wukong-robot里openai那样单独走代理的方法。
我自己也写了一个查询空气质量的代码，但现在被墙了就不行了。

openai有proxy的属性，如果下面的代码也单独走代理，如何写呢？

import urllib.request
from bs4 import BeautifulSoup

def AirQ(location):
    AQI = {'pm25':'','pm10':'','o3':'','no2':'','so2':'','co':'','t':'','p':'','h':'','w':''}
    for x in AQI:
        AQI[x] = '-100'
    site = r'https://aqicn.org/city/' + '' + location + '/m/'
    html = urllib.request.urlopen(site)
    htmltxt = BeautifulSoup(html,features='html.parser')
    airaqi = str(htmltxt)  
    stat_start = airaqi.find(r"iaqi") + 8
    stat_end = airaqi.find(r"]]}]") + 3
    model = airaqi[stat_start:stat_end] # AQI指数  
    air_stat = model.split('{')
    for x in air_stat :
        parameters = x[4:].split(']')
        parameter = parameters[0]
        AQI[parameter.split('\"')[1]] = parameter.split('\"')[4].split('[')[1].split(',')[0]
    return(AQI)

**Comment by wzpan** [comment]
requests 支持代理：https://zhuanlan.zhihu.com/p/79466893
你可以改用 requests 来实现请求。

**Comment by prairiewolf11** [comment]
好的，感谢感谢。
