### ISSUE TITLE
”最怕空气突然安静“－升级体验

### ISSUE THREAD

**Issue by prairiewolf11** [wzpan/wukong-robot#221]
openai的响应基本是12秒+，这段时间就是单纯的等待。要是能在这段时间让机器人随机说1句话，体验会好很多。
大概是下面的样子，我就抛砖引玉了。
        answer = ['嗯嗯，让我好好想想','给我10秒钟我给你个完美的答案','我去上网查查，请稍等片刻']
        self.say(answer[random.randint(0,len(answer)-1)], cache=True)

**Comment by wzpan** [comment]
我觉得 ChatGPT 支持流式#217 也许可以更好的解决输出慢的问题。
