### ISSUE TITLE
绘画代码，不知愿否加到wukong-robot里。虽然不适合音箱对话，但用“会话”页面还是很棒的

### ISSUE THREAD

**Issue by prairiewolf11** [wzpan/wukong-robot#222]
以下代码是OpenAI的画图功能，我单独的程序运行很棒。加到wukong-robot里也会很棒
    def create_img(self, query):
        try:
            response = openai.Image.create(
                prompt=query,    #图片描述
                n=1,             #每次生成图片的数量
                size="512x512"   #图片大小,可选有 256x256, 512x512, 1024x1024
            )
            image_url = response['data'][0]['url']
            #print("[OPEN_AI] image_url={}".format(image_url))
        except Exception as e:
            print(e)
            return None
        return image_url

**Comment by wzpan** [comment]
不妨考虑贡献成第三方插件：https://wukong.hahack.com/#/writing-skill-publish

**Comment by prairiewolf11** [comment]
好主意。我试试

**Comment by wzpan** [comment]
PS：你可以把 wukong-robot 插件开发的教程精简一些丢给 ChatGPT 让它帮你生成。

这是我 prompt 后生成的结果，除了对 query 的解析以及 openai 的 key 读取有点毛病之外其他的看不出啥问题。简单再调优下即可用。

``` py
# -*- coding: utf-8-*-
import openai
from robot.sdk.AbstractPlugin import AbstractPlugin

class Plugin(AbstractPlugin):

    def __init__(self, con):
        super(Plugin, self).__init__(con)
        # 设置 OpenAI API 密钥
        openai.api_key = "your_openai_api_key"

    def generate_image_url(self, query):
        try:
            # 调用 OpenAI 的 Image.create API
            response = openai.Image.create(prompt=query, size="512x512")
            image_url = response.get("url")
            return image_url
        except Exception as e:
            self.logger.error("Error generating image: {}".format(e))
            return None

    def handle(self, text, parsed):
        query = parsed.get("query")
        if query:
            image_url = self.generate_image_url(query)
            if image_url:
                self.say("根据你的请求，我生成了这张图片：{}".format(image_url))
            else:
                self.say("抱歉，我无法生成你要求的图片。")
        else:
            self.say("请提供一个有效的查询以生成图片。")

    def isValid(self, text, parsed):
        return "生成图片" in text
```

**Comment by prairiewolf11** [comment]
# -*- coding: utf-8 -*-
# author: prairiewolf
# OpenAI绘画

from robot import config, constants, logging
from robot.sdk.AbstractPlugin import AbstractPlugin

logger = logging.getLogger(__name__)
import os
import time
import openai
import requests

class Plugin(AbstractPlugin):
    def __init__(self, con):
        super(Plugin, self).__init__(con)
        openai.api_key = config.get("/openai/openai_api_key", '')
        proxy = config.get("/openai/proxy", '')
        ''' 不用代理也能画,用了代理画得慢。
        if proxy:
            openai.proxy = proxy
        '''
    def generate_image_url(self, query):
        try:
            response = openai.Image.create(
                prompt=query,    #图片描述
                n=1,             #每次生成图片的数量
                size="512x512"   #图片大小,可选有 256x256, 512x512, 1024x1024
            )
            image_url = response['data'][0]['url']
            return image_url

        except Exception as e:
            self.logger.error("Error generating image: {}".format(e))
            return None

    def handle(self, text, parsed):
        headers = {
    'Host': 'www.prairiewolf.com',
    'Upgrade-Insecure-Requests': '1',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36',
}
        dest_path = config.get("/camera/dest_path", os.path.expanduser("~/pictures"))
        dest_file = os.path.join(dest_path, "%s.jpg" % time.strftime("%Y-%m-%d_%H:%M:%S",time.localtime()))
        if text:
            try:
                image_url = self.generate_image_url(text)
                r = requests.get(image_url)
                if r.status_code == 200:
                    with open(dest_file, 'wb') as f:
                        f.write(r.content)
                    
                    photo_url = "http://{}:{}/photo/{}".format(
                    config.get("/server/host"),
                    config.get("/server/port"),
                    os.path.basename(dest_file),
                )
                    self.say(photo_url)
                else:
                    self.say("抱歉，网络连接失败。")
            except:
                self.say("OpenAI未能生成图片。")
    def isValid(self, text, parsed):
        return text[0] == "画"

**Comment by prairiewolf11** [comment]
![image3](https://user-images.githubusercontent.com/8274686/228817751-53b29cf2-0e1f-4038-a291-613fdc9fa846.jpg)
生成的logo
