### ISSUE TITLE
在config.yml里怎么没有ChatGPT的选项了？

### ISSUE THREAD

**Issue by nyancatx** [wzpan/wukong-robot#223]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装

**操作系统**

WLS

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

具体说明下问题

![image](https://user-images.githubusercontent.com/77722739/229132700-a2f392f4-7f0e-4385-975e-f7e69bb31658.png)

我记得以前在config.yml的这个地方是有ChatGPT的选项的

删掉重新创建还是这样

是现在不能用ChatGPT当聊天机器人了吗？

**Comment by wzpan** [comment]
主干是有的：

<img width="368" alt="image" src="https://user-images.githubusercontent.com/1631405/229271247-3324c674-9b21-430c-b14b-a927342face1.png">

https://github.com/wzpan/wukong-robot/blob/ee87f7d248aa13554058a4c06cbdcb7f39dd3973/static/default.yml

而如果你是自己的 config.yml ，为了避免破坏用户数据，这个配置是不会随着 wukong-robot 的更新而被修改的。所以需要用户自行新增配置。
