### ISSUE TITLE
config.yml配置不生效

### ISSUE THREAD

**Issue by sj1531122** [wzpan/wukong-robot#226]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

docker安装

**操作系统**

Ubuntu 14.04

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

  docker 启动后一直提示语音合成失败，我怀疑是config.yml没有生效导致，后根据安装指导:
![image](https://user-images.githubusercontent.com/127570353/229272742-9846516a-e7ec-4385-8b69-68abd1c8e276.png)
找不到$HOME/.wukong/config.yml，导致真实的config.yml无法配置，请问下这种情况怎么解决？

**Comment by wzpan** [comment]
第一次启动的时候会提示你是否要创建一个 config.yml 。

<img width="671" alt="image" src="https://user-images.githubusercontent.com/1631405/229275732-63f52e2d-5daa-40d5-9a40-de10aa7a5587.png">

如果错过了，直接拷贝一份过去即可。

``` bash
cp static/default.yml ~/.wukong/config.yml
```

**Comment by sj1531122** [comment]
从ubuntu拷贝config文件过去就生效了，已解决，谢谢!
