### ISSUE TITLE
problem with line wrapping

### ISSUE THREAD

**Issue by dyizheng** [wzpan/wukong-robot#231]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装

**操作系统**

Raspbian 

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

具体说明下问题
wukong-robot edition 3.50
when wukong-robot replies to user with long text ，there is a problem with line wrapping. The scroll bar appeared. Text can not display completely at one time.
![image](https://user-images.githubusercontent.com/87369532/230726177-ed5983b4-0e01-4d5e-bc1d-d57e38ee8b90.png)

**复现步骤**

具体描述下复现步骤

 let wukong-robot reply to long text user without period.

**Comment by prairiewolf11** [comment]
一切正常
![无标题](https://user-images.githubusercontent.com/8274686/230727107-6f574cae-0e1a-4cbc-9276-a6f51c389801.png)

**Comment by wzpan** [comment]
已合入
