### ISSUE TITLE
chatgpt的流式请求地址没有引用api_base

### ISSUE THREAD

**Issue by caotao94** [wzpan/wukong-robot#232]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装

**操作系统**

debian11

**问题描述**

chatgpt的流式请求地址没有引用api_base

**复现步骤**

报错信息：
`023-04-08 22:34:03,564 - server.server - server.py - onResp - line 141 - INFO - response msg: request error:
HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fdddf2ad820>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
`

**Comment by wzpan** [comment]
已修复，提交到了主干。可以更新试试。

**Comment by caotao94** [comment]
测试了下没问题了
