### ISSUE TITLE
可以做合成小说播放语音的功能吗？

### ISSUE THREAD

**Issue by prairiewolf11** [wzpan/wukong-robot#234]
如果基于edge-TTS合成的话，可以大量合成，其他的在线TTS几乎都要耗调用量。

**Comment by wzpan** [comment]
这个更像是 wukong-robot 的应用场景。更适合用第三方技能插件的方式来实现。

详见 [技能开发](https://wukong.hahack.com/#/writing-skill) 学习如何开发插件，也欢迎 [贡献](https://wukong.hahack.com/#/writing-skill-publish) 你的技能。

如果希望找队友一起合作开发，不放移步到 [Discussion-插件开发](https://github.com/wzpan/wukong-robot/discussions/categories/%E6%8F%92%E4%BB%B6%E5%BC%80%E5%8F%91) 板块发帖交流。

**Comment by prairiewolf11** [comment]
好的。
