### ISSUE TITLE
国内叮咚智能音箱下架了。能用这个程序刷机吗

### ISSUE THREAD

**Issue by xiangfeigao** [wzpan/wukong-robot#245]
国内京东前一个月宣布智能音箱叮咚下架了。能否把这个刷机进去，付费都可以

**Comment by shaojs321** [comment]
能在天猫精灵上刷吗

**Comment by wzpan** [comment]
@shaojs321 没有刷机的说法的。只能联动。方案可以参考小爱音箱的联动方式，如果你有接口能实时获取到天猫精灵的聊天记录就能实现。
