### ISSUE TITLE
谁乱改的，250吗？

### ISSUE THREAD

**Issue by g-wellsa** [wzpan/wukong-robot#256]
![image](https://user-images.githubusercontent.com/4343884/235366572-cd4fc601-d166-47c8-b41d-7897323a2d9f.png)
一边是_asr 实际被改成_yuyin

**Comment by jack9603301** [comment]
@g-wellsa 在开源社区注意文明和社交素质

**Comment by wzpan** [comment]
@g-wellsa 请具体说明问题是啥。
