### ISSUE TITLE
接入gpt4free

### ISSUE THREAD

**Issue by haozhuoyi** [wzpan/wukong-robot#266]
不知能否接入gpt4free，使用免费key，感觉是个不错的想法，虽然不太道德，但是能降低chatgpt的使用门槛

**Comment by wzpan** [comment]
技术上肯定可以实现，而且很简单。最近在尝试编译新的docker镜像，还陷在坑里。欢迎大家PR~

**Comment by haozhuoyi** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by haozhuoyi** [comment]
好嘞

**Comment by prairiewolf11** [comment]
#261 
这个可以免费使用ChatGPT

**Comment by haozhuoyi** [comment]
> 

才看到，十分感谢，想问下他这个项目其实是利用网页版gpt进行提问吗

**Comment by haozhuoyi** [comment]
> #261 这个可以免费使用ChatGPT

才看到，十分感谢，想问下他这个项目其实是利用网页版gpt进行交互嘛

**Comment by prairiewolf11** [comment]
对的，很好用。
https://github.com/prairiewolf11/ChatGPT
