### ISSUE TITLE
写沉浸式插件出错

### ISSUE THREAD

**Issue by nameluck** [wzpan/wukong-robot#28]
我想试着写一下沉浸式插件，那个isVaildImmersive函数里面应该怎么写啊，我这样写的话，一说退出，并没有进入if，又会重新进入handel函数，说“进入超声波测距模块”

![et wby78 u6w6v8ibwbmka](https://user-images.githubusercontent.com/37497053/53630166-64543f00-3c4a-11e9-8314-2b195304a0df.png)

**Comment by wzpan** [comment]
试试把 `if` 放方法开头。

另外你的代码风格不够好，类声明和头部之间要隔开两行；成员方法之间至少隔 1 行。
建议了解一下 pep8 代码规范。

**Comment by nameluck** [comment]
把if放在handle方法开头也是一样，同样不会进入if内部
![image](https://user-images.githubusercontent.com/37497053/53632967-31fa1000-3c51-11e9-8572-6bdb7e9477d5.png)
这是控制台消息，当我说退出的时候，会重新进入此技能

**Comment by wzpan** [comment]
你在 if 结束后加了 return 没？

**Comment by nameluck** [comment]
没有啊，我看您写的模板里面没有return呀

**Comment by wzpan** [comment]
`return` 为什么要放进我的模板？这不是基本的语法么？

你把那段 `if` 放开头，但又没有在结束后return掉，那么即使进去了 `if` 块，执行完还是会继续执行下面的代码的呀。

**Comment by wzpan** [comment]
@nameluck 这个问题解决了没

**Comment by nameluck** [comment]
解决啦  谢谢老大啦

**Comment by wzpan** [comment]
@nameluck 请关单
