### ISSUE TITLE
行空板 使用api_base方式调用openai机器人 api_key对象属性报错

### ISSUE THREAD

**Issue by dnvljty** [wzpan/wukong-robot#282]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装

**操作系统**

行空板

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

和#272有点像，但尝试修改api_base没有解决问题。

报错信息
![微信截图_20221128115710](https://github.com/wzpan/wukong-robot/assets/17612655/d64019aa-eea7-4c78-90a3-c133e3caea30)

配置信息
![222](https://github.com/wzpan/wukong-robot/assets/17612655/ff02efc3-1353-46f5-822e-5c614eb7f701)

**Comment by wzpan** [comment]
可能是你的 yaml 编写格式问题。openai_api_key 那个地方，试试用 '' 包住你的值。比如：

```
# OpenAI(ChatGPT) 机器人
# 使用科学上网工具到 https://platform.openai.com
# 注册一个账号，获得 openai_api_key 后填到下面的配置中即可
openai:
    openai_api_key: 'sk-xxxxxxxxxxxxxxxxxxxxxxxxxx' 
```

**Comment by dnvljty** [comment]
谢谢回复，截图没截到，是使用英文单引号包住的。设备不在手边，晚上我再试试。

**Comment by dnvljty** [comment]
![222](https://github.com/wzpan/wukong-robot/assets/17612655/01826777-3bab-43c9-9bf5-88f5ebabf821)
使用代理，报一样的错误
![222](https://github.com/wzpan/wukong-robot/assets/17612655/0a154db3-9956-4d7d-81aa-815bc4af19ce)
这是行空板里的ai.py
![image](https://github.com/wzpan/wukong-robot/assets/17612655/853df5a9-4e93-4c8a-980c-bc872d54dcae)
![image](https://github.com/wzpan/wukong-robot/assets/17612655/bbcb816f-bff0-4005-a7c4-5668a42eb27a)
![image](https://github.com/wzpan/wukong-robot/assets/17612655/9a752aee-5d4e-44bb-b015-6923f4935d62)

**Comment by wzpan** [comment]
试试加个环境变量：

``` bash
export OPENAI_API_KEY='你的 KEY 值'
```

**Comment by dnvljty** [comment]
已解决。

**Comment by dnvljty** [comment]
原因是手动安装过程中未安装openai的库
