### ISSUE TITLE
Conversation

### ISSUE THREAD

**Issue by nameluck** [wzpan/wukong-robot#29]
![image](https://user-images.githubusercontent.com/37497053/53690403-d3de4180-3da4-11e9-8f76-175fcfe45e95.png)

**Comment by nameluck** [comment]
这是今早上起来更新的最新版本

**Comment by wzpan** [comment]
我搜了整个工程没有发现这个变量。请检查下你的超声波插件。

**Comment by nameluck** [comment]
![image](https://user-images.githubusercontent.com/37497053/53690455-ac3ba900-3da5-11e9-9d21-c7ddddde0b0f.png)

**Comment by nameluck** [comment]
我无论说啥  都无法匹配技能呀

**Comment by wzpan** [comment]
我已经加过 pyflakes 用作 build test，而当前状态是 passing 的。所以我不认为新版本会有这个未定义的语法错误。
