### ISSUE TITLE
希望能支持手动唤醒接口。

### ISSUE THREAD

**Issue by atjason** [wzpan/wukong-robot#292]
现在的语音唤醒，总是有唤醒不灵敏、语音播放过程中被意外唤醒。所以，我想加个按钮，改成手动唤醒。

希望能开放个 API 接口，可以通过 http 请求主动唤醒，开始监听语音，并进行之后的流程。

**Comment by atjason** [comment]
目前，我在 `/chat` 接口中，加了下面的补丁。这样，传入 `start` 参数时，能进入监听模式。

```
            elif self.get_argument("type") == "start":
                res = {"code": 0, "message": "ok"}
                self.write(json.dumps(res))

                wukong._detected_callback(False)
                wukong.conversation.interrupt()
                query = wukong.conversation.activeListen()
                wukong.conversation.doResponse(query)
```

**Comment by wzpan** [comment]
[LifeCycleHandler](https://github.com/wzpan/wukong-robot/blob/master/robot/LifeCycleHandler.py) 里就有很多手动唤醒的方式。比如脑机、摇一摇等等。

**Comment by atjason** [comment]
收到。目前我的上面方法暂时够用。并且由于是 http 请求，唤醒可以和 wukong 解耦。
