### ISSUE TITLE
https://snowboy.hahack.com/唤醒词训练网站进不去了

### ISSUE THREAD

**Issue by AlbertDeng11** [wzpan/wukong-robot#308]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**问题描述**

我想要训练自己的唤醒词模型，但是使用https://snowboy.hahack.com/时，发现无法进入该网站。请问作者是否关闭了该网站，如果不再提供训练服务，我应该如何在自己的设备/服务器上进行训练？

**Comment by wzpan** [comment]
已修复。请重新测试：https://snowboy.hahack.com/

**Comment by AlbertDeng11** [comment]
已解决。
