### ISSUE TITLE
开机的一段男声能不能修改？

### ISSUE THREAD

**Issue by exbob** [wzpan/wukong-robot#32]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装

**操作系统**

Raspbian Stretch

**问题描述**

启动时会说一段男声，这段声音怎么自定义？

**Comment by wzpan** [comment]
清除缓存后就会重新合成新的语音

**Comment by exbob** [comment]
> 清除缓存后就会重新合成新的语音

只能自动合成，不能自定义吗？

**Comment by musistudio** [comment]
修改wukong.py文件里的那一段文字

**Comment by exbob** [comment]
> 修改wukong.py文件里的那一段文字

谢谢了

**Comment by MIss-luoyu** [comment]
> > 修改wukong.py文件里的那一段文字
> 
> 谢谢了

请问，你修改好了嘛？我修改了wukong.py文件的那一段字，结果提示音还是”师父你好“，请问要怎么解决呢？

**Comment by musistudio** [comment]
> 请问，你修改好了嘛？我修改了wukong.py文件的那一段字，结果提示音还是”师父你好“，请问要怎么解决呢？
@MIss-luoyu 清除缓存后重试
