### ISSUE TITLE
关于勿扰模式的唤醒词

### ISSUE THREAD

**Issue by Jesse54211** [wzpan/wukong-robot#33]
我已经在配置文件里边把使用热词进入退出勿扰模式那个开关打开之后，我说了进入勿扰模式的热词:魔镜别吵之后，他还是提示错误(已经训练好了，放在指定目录下了)
/hotword/hotword_switch not specified in profile defaulting to false

**Comment by wzpan** [comment]
https://wukong.hahack.com/#/run

按照这里的教程添加一个 `hotword_switch` 配置，值设为 false 。

**Comment by Jesse54211** [comment]
设置过了  也不行

**Comment by wzpan** [comment]
说错，值设为 true ……
