### ISSUE TITLE
docker镜像启动时出现’can't start new thread’的错误信息，导致程序无法正常运行

### ISSUE THREAD

**Issue by kulina** [wzpan/wukong-robot#332]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

docker安装

**操作系统**

Ubuntu 16.04

**程序启动相关**

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

试用最新的docker镜像，启动服务时出现如下问题
<img width="934" alt="1" src="https://github.com/wzpan/wukong-robot/assets/14291067/900f36f6-24f4-47b5-9530-b73e1f05724a">

**Comment by wzpan** [comment]
是今天你在群里反馈的问题不？目测是windows + 虚拟机 + docker环境下遇到的问题。

**Comment by wzpan** [comment]
在群里已经沟通解决，关闭本issue。
