### ISSUE TITLE
麦克风

### ISSUE THREAD

**Issue by nameluck** [wzpan/wukong-robot#34]
默认的录音方式，arecord无法录音，修改过配置文件，arecord又能录音了，但今天什么也没干，麦克风又不能arecord录音了，这个老是反复出现，不知道为啥，在哪里可以修改悟空的录音方式啊？可不可以在后面加上plughw:1,0，这样arecord无法录音，也就无法影响悟空了，

**Comment by wzpan** [comment]
你提的问题本质上和 wukong-robot 无关，是声卡配置的问题。
而我调用录音走的是和 snowboy 一样的流程和代码。

**Comment by nameluck** [comment]
我知道是声卡的问题，可是我特别迷 啊，这为啥我什么配置都没变，默认声卡又发生了改变呢
![image](https://user-images.githubusercontent.com/37497053/54065781-5ca32480-4260-11e9-8a86-b1866271c84d.png)

**Comment by nameluck** [comment]
变来变去变了两次了，最关键的是很多修改声卡的教程没有用啊，我这个配置之前有用着 呢，现在又没用了

**Comment by Jesse54211** [comment]
我也有这个问题，录音用不了。命令行用arecord 加上plughw:1,0又可以。

**Comment by wzpan** [comment]
wukong-robot并不是调用arecord录音的，加不了 pluginw:1,0 。你们需要自己解决这个问题。

**Comment by ZhangJun1015** [comment]
> 我也有这个问题，录音用不了。命令行用arecord 加上plughw:1,0又可以。
你这个应该是默认的录音设备不对，所以需要用 plughw:1,0来指定录音设备。

解决方法得看具体的硬件设备，有的硬件安装驱动之后会修改系统的设置，有一些需要手动修改。我之前使用ReSpeaker 4-Mic （http://www.sirit.com.cn/index.php/archives/329/）也是折腾了好久，系统老是不默认它为录音设备。

**Comment by ZhangJun1015** [comment]
> 我知道是声卡的问题，可是我特别迷 啊，这为啥我什么配置都没变，默认声卡又发生了改变呢
> ![image](https://user-images.githubusercontent.com/37497053/54065781-5ca32480-4260-11e9-8a86-b1866271c84d.png)

是不是和启动顺序有关，启动时找不到录音设备，所以修改了配置文件。

**Comment by nameluck** [comment]
我之前没有这种状况，使用usb接口的gps模块后，从gps模块获取数据后，arecord demo.wav就不能录音了，需要加参数指定才行，我配置.arecordrc也没有用。

**Comment by Jesse54211** [comment]
我跟你的情况一样，比如这次开机没有插入麦克风，下次开机插上麦克风 就不能用了  要确保每次开机都要插着麦克风。录音才正常

**Comment by nameluck** [comment]
那你下次开机插上麦克风就又好了么？那不是没啥大问题么。我是用过gps后，arecord demo.wav始终录不上音了，不管下次开机插没插麦克风。

**Comment by Jesse54211** [comment]
不。只要有一次开机不插麦克风，以后都不能录音了。

**Comment by nameluck** [comment]
哇 你这一说，我感觉好像和用gps没关呀，我为了测试gps模块，把树莓派放在窗户边，没插麦克风，然后回来插上麦克风就录不上音了，我一直以为和gps有关。

**Comment by wzpan** [comment]
https://raspberrypi.stackexchange.com/questions/54199/my-asoundrc-is-modified-every-reboot

my asoundrc is modified every reboot

**Comment by wzpan** [comment]
久无回复，暂时关闭本issue。有问题再重开。
