### ISSUE TITLE
[ERROR -9997]Invalid sample rate

### ISSUE THREAD

**Issue by Cydia2018** [wzpan/wukong-robot#36]
**安装方式**
群友提供的一键安装

**操作系统**

Raspbian Stretch

**问题描述**

离线唤醒机制初始化失败：[ERROR -9997]Invalid sample rate
我尝试直接rec temp.wav测试，发现可以正常录制声音，求大神帮忙解决一下。

**Comment by wzpan** [comment]
arecord temp.wav 能工作不？

rec 是 Mac 下测试用的。Linux 下应该用 arecord.

**Comment by Cydia2018** [comment]
> arecord temp.wav 能工作不？
> 
> rec 是 Mac 下测试用的。Linux 下应该用 arecord.

您好，使用arecord命令是这种情况：
我在/home/pi目录下用 arecord test.wav 可以正常录制，但是在根目录下就会报错：arecord: main:788: audio open error: 没有那个文件或目录
并且报错之后rec test.wav命令也跟着报错：
rec FAIL formats: can't open input  `default': snd_pcm_open error: No such file or directory
烦请您费心帮我看一下，谢谢。

**Comment by wzpan** [comment]
你拉仓库以及执行一些无需系统权限的命令的时候是不是都用了sudo？

**Comment by Cydia2018** [comment]
> 你拉仓库以及执行一些无需系统权限的命令的时候是不是都用了sudo？

我安装的时候为了方便，直接用了网友提供的方案：sudo wget http://wukong-install.oss-cn-hangzhou.aliyuncs.com/install.sh && sudo chmod 777 install.sh &&./install.sh
我再重新手动安装一下试试吧，谢谢。

**Comment by Cydia2018** [comment]
> 你拉仓库以及执行一些无需系统权限的命令的时候是不是都用了sudo？

您好，我在/home/pi目录下重新安装了wukong-robot，然后没有采样率错误的提示了。但是初始的语音不播报了，麦克风也接收不到指令，程序停在下面的状态“：
……
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

不知道这是上面原因，感谢您的帮助。

**Comment by wzpan** [comment]
arecord 、aplay 能正常工作吗？

**Comment by Cydia2018** [comment]
> arecord 、aplay 能正常工作吗？

直接用arecord test.wav或者aplay test.wav都不能录制或播放声音
但是用命令arecord -D "plughw:1,0" temp.wav或aplay -D "plughw:0,0" temp.wav指定设备后就能正常录制和播放了。
我们的.asoundrc文件如下：

pcm.!default {
        type asym
        playback.pcm {
                type plug
                slave.pcm "hw:0,0"
        }
        capture.pcm {
                type plug
                slave.pcm "hw:1,0"
        }
}

我认为设备没有指定错误，但是却不能用，请问这是什么原因，谢谢。

**Comment by wzpan** [comment]
只有直接 arecord temp.wav，aplay temp.wav 都能正常工作才算配好麦克风，然后再尝试 wukong-robot。

**Comment by Cydia2018** [comment]
> 只有直接 arecord temp.wav，aplay temp.wav 都能正常工作才算配好麦克风，然后再尝试 wukong-robot。

请问该怎么解决，因为我看命令中指定的设备和.asoundrc文件是一样的，但是却有错误

**Comment by wzpan** [comment]
贴下你 `arecord -l` 和 `aplay -l` 的结果

**Comment by Cydia2018** [comment]
> 贴下你 `arecord -l` 和 `aplay -l` 的结果。建议提问题的时候尽量给多点信息。

arecord -l
**** List of CAPTURE Hardware Devices ****
card 1: Device [USB PnP Sound Device], device 0: USB Audio [USB Audio]
  Subdevices: 0/1
  Subdevice #0: subdevice #0

aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 6/7
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

真是麻烦您了

**Comment by wzpan** [comment]
我看到你接了HDMI，是不是被树莓派强制设成HDMI输出了。试试进 raspi-config，找到 interface 里 Audio 的设置，改成 force 3.5mm 那个。

**Comment by Cydia2018** [comment]
> 我看到你接了HDMI，是不是被树莓派强制设成HDMI输出了。试试进 raspi-config，找到 interface 里 Audio 的设置，改成 force 3.5mm 那个。

没有，我没有接HDMI，不过我在叮当下面重装了wukong-robot，可以用了，谢谢。

**Comment by nataliejupiter** [comment]
懒得喷，同样的问题，真是给我整出脾气了
