### ISSUE TITLE
拍照的配置文件，不发送邮箱，拍照后依然会播报发送邮箱

### ISSUE THREAD

**Issue by nameluck** [wzpan/wukong-robot#37]
摄像头拍照的配置文件设置成了：不发送邮箱（false），拍照后依然会播报发送邮箱，我邮箱其实配置文件都没写呢，肯定不影响使用，就是有点怪呀

**Comment by wzpan** [comment]
那个 `sendToUser` 的配置有问题。应该是 `send_to_user` 。

**Comment by wzpan** [comment]
问题应该已解决，关闭本单。
