### ISSUE TITLE
树莓派3B+安装成功启动失败

### ISSUE THREAD

**Issue by liziru** [wzpan/wukong-robot#38]
问题描述：我使用树莓派3B+环境搭建，根据一键式脚本安装（https://github.com/musistudio/wukong-robot-install-script）,提示安装成功后执行python3 wukong.py 报错
问题显示：
 python3 wukong.py 

********************************************************
*          wukong-robot - 中文语音对话机器人           *
*          (c) 2019 潘伟洲 <m@hahack.com>              *
*     https://github.com/wzpan/wukong-robot.git        *
********************************************************

            如需退出，可以按 Ctrl-4 组合键。

asr_engine not specified in profile, defaulting to 'tencent-asr'
2019-03-20 09:25:33,820 - robot.ASR - INFO - 使用 tencent-asr ASR 引擎
tencent_yuyin not specified in profile, defaulting to '{}'
2019-03-20 09:25:33,856 - robot.Conversation - CRITICAL - 对话初始化失败：__init__() missing 3 required positional arguments: 'appid', 'secretid', and 'secret_key'
first_name not specified in profile, defaulting to '主人'
2019-03-20 09:25:33,890 - robot.Conversation - ERROR - 保存缓存失败！
statistic not specified in profile, defaulting to 'True'
/server/enable not specified in profile, defaulting to 'False'
robot_name_cn not specified in profile, defaulting to '孙悟空'
active_mode not specified in profile, defaulting to 'False'
麻烦帮忙看一下，挺急的

**Comment by wzpan** [comment]
一键脚本非本项目提供，请提给一键安装脚本项目寻求帮助。

**Comment by liziru** [comment]
因为我自己按照教程手动安装了一遍，也是上述问题。后来才使用的一键安装脚本，问题也是如此。

**Comment by liziru** [comment]
python3 wukong.py init

********************************************************
*          wukong-robot - 中文语音对话机器人           *
*          (c) 2019 潘伟洲 <m@hahack.com>              *
*     https://github.com/wzpan/wukong-robot.git        *
********************************************************

            如需退出，可以按 Ctrl-4 组合键。


asr_engine not specified in profile, defaulting to 'tencent-asr'
2019-03-20 10:02:30,954 - robot.ASR - INFO - 使用 tencent-asr ASR 引擎
tencent_yuyin not specified in profile, defaulting to '{}'
2019-03-20 10:02:30,973 - robot.Conversation - CRITICAL - 对话初始化失败：__init__() missing 3 required positional arguments: 'appid', 'secretid', and 'secret_key'
first_name not specified in profile, defaulting to '主人'
2019-03-20 10:02:30,988 - robot.Conversation - ERROR - 保存缓存失败！
active_mode not specified in profile, defaulting to 'False'

**Comment by liziru** [comment]
@wzpan 能帮忙看一下吗

**Comment by wzpan** [comment]
你的 tencent_yuyin 配置了没？

**Comment by wzpan** [comment]
是不是还没配 config.yml ？https://wukong.hahack.com/#/configure

**Comment by liziru** [comment]
好的多谢
