### ISSUE TITLE
安装wukong会导致respaker失效

### ISSUE THREAD

**Issue by ikiler** [wzpan/wukong-robot#41]
本来respaker已经好用 aplay和arecord都正常，但是安装之后就失效了，就算修改.asround也无济于事，怎么也修改不了默认声卡，只能重装系统

**Comment by wzpan** [comment]
wukong只是纯软件，不会导致respeaker失败。
你可能要怀疑的是 wukong-robot 的某些依赖影响了使用，比如pulseaudio。

**Comment by ikiler** [comment]
> wukong只是纯软件，不会导致respeaker失败。
> 你可能要怀疑的是 wukong-robot 的某些依赖影响了使用，比如pulseaudio。

之前一直是好用的，不知道为什么，我重新安装之后就这样了 aplay播放的默认声卡调不到respaker

**Comment by 5high** [comment]
我也是同样问题，刚装好respeaker能正常录放，安装wukong后就不能录放。

**Comment by 5high** [comment]
> wukong只是纯软件，不会导致respeaker失败。
> 你可能要怀疑的是 wukong-robot 的某些依赖影响了使用，比如pulseaudio。


我测试过了，确实是这个影响的，但是我们一点儿办法都没有吗？

阵列麦克风就白买了吗？

**Comment by wzpan** [comment]
你应该怀疑的是 respeaker 的驱动问题。目前一种可能的问题是 respeaker 的驱动在新的树莓派系统上会有兼容问题。

群里有用户遇到类似的问题，通过重装系统+respeaker驱动解决。

**Comment by wzpan** [comment]
@5high 如果无法解决，请联系 respeaker 售后。

wukong-robot 非 respeaker 卖方，无法提供硬件技术支持。

**Comment by ikiler** [comment]
> > wukong只是纯软件，不会导致respeaker失败。
> > 你可能要怀疑的是 wukong-robot 的某些依赖影响了使用，比如pulseaudio。
> 
> 我测试过了，确实是这个影响的，但是我们一点儿办法都没有吗？
> 
> 阵列麦克风就白买了吗？

你可以试试旧版驱动或者先安装wukong再安装驱动，反正我重装了好几遍才好

**Comment by wzpan** [comment]
最近也遇到 respeaker 是用不了的问题。初步可以判定是 pulseaudio 与 Respeaker 的兼容性问题。

解决方法：

1. 重刷树莓派镜像；
2. 先安装好 pulseaudio ：

``` sh
sudo apt-get install python-pyaudio python3-pyaudio sox pulseaudio libsox-fmt-all ffmpeg
```

3. 安装 respeaker 的驱动；
4. 安装 wukong-robot 。

这样就可以正常使用。

**Comment by tonytan1701** [comment]
ReSpeaker 2-Mics Pi HAT其实是可以用的，我没有使用pulseaudio而是用了bluealsa，听说是pulseaudio确实在树莓派上有一定的问题。【切记：使用bluealsa的话，一定要删干净pulseaudio，https://yanke.info/?id=108】

目前用音频输出用蓝牙音箱，输入用ReSpeaker，感觉不错。

**Comment by wzpan** [comment]
@tonytan1701 谢谢尝试。我也试试

**Comment by faweiz** [comment]
Make a new folder name "pulse_config_2mic" and copy files from …_4mic and upload to the pi then follow instruction in the gitthub page
(https://github.com/seeed-studio-projects/seeed-voicecard/tree/v6.1/pulseaudio)
