### ISSUE TITLE
request 阻塞

### ISSUE THREAD

**Issue by seeding-x** [wzpan/wukong-robot#43]
在语音合成或者tuling请求接口阻塞后会导致无法唤醒，处于一直阻塞的状态。您这边有什么建议么？

**Comment by wzpan** [comment]
是不是用了老版本？我在 1.3.9 就通过增加超时修了这个问题。

**Comment by seeding-x** [comment]
是最新的版本没错，我看到1.3.9的版本只修改了上报服务器（statistic.py）的超时问题，机器人聊天，语音识别，以及语音合成接口仍然处于没有timeout状态

**Comment by wzpan** [comment]
机器人聊天、语音识别和合成这三个都是必须路径，加了timeout都工作不了了。
如果超时，建议更换其他服务。

**Comment by seeding-x** [comment]
必须路径的意思是？加timeout应该不会有程序上的bug，我的想法是这些接口添加了timeout之后，若是超时直接报错然后忽略过去，这样的话就不会导致阻塞了。

**Comment by wzpan** [comment]
从你的描述来看，这种阻塞出现的几率比较大。即使加了timeout，频繁报错然后让你重试也很影响体验。
我建议你应该考虑换ASR、TTS 等服务，要么就是换网络。

**Comment by seeding-x** [comment]
了解
