### ISSUE TITLE
按照教程git cherry-pick呼吸灯补丁识别，提示版本不对.

### ISSUE THREAD

**Issue by 5high** [wzpan/wukong-robot#44]
git cherry-pick c12ca91

fatal: bad revision 'c12ca91'

**Comment by wzpan** [comment]
你可以先参考dingdang-robot的这个改动自己集成下呼吸灯：

https://github.com/wzpan/dingdang-robot/commit/2cd61db29a8a0431ea52dc37076a6492b6971797

**Comment by 5high** [comment]
可惜我是小白，不知道如何集成。

**Comment by wzpan** [comment]
切 respeaker-1.4.8 分支试试。

``` sh
git checkout respeaker-1.4.8
```

**Comment by 5high** [comment]
git我只知道clone ，还是算了，我放弃呼吸灯，感谢回答。
