### ISSUE TITLE
树莓派3B安装成功，启动失败

### ISSUE THREAD

**Issue by LJW813120** [wzpan/wukong-robot#46]
环境：树莓派3B  Raspbian系统
问题描述：在启动悟空时，执行 Python3 wukong.py，报错，找不到模块pyaudio，手动安装与一键脚本安装皆出现该问题
报错信息如下：
Traceback (most recent call last):
  File "wukong.py", line 2, in <module>
    from snowboy import snowboydecoder
  File "/home/pi/wukong-robot/snowboy/snowboydecoder.py", line 4, in <module>
    import pyaudio
ImportError: No module named 'pyaudio'
本人小白一个，不是很懂，在网上没有找到相关的信息与解决方法，望解决告知，多谢

**Comment by wzpan** [comment]
这里不是写了吗？你的 pyaudio 没安装好啊。你确定前面安装步骤都成功了？

**Comment by LJW813120** [comment]
> 这里不是写了吗？你的pyaudio没安装好啊。你确定前面安装步骤都成功了？

刚刚检查了一下发现pip命令安装时报错Failed building wheel for pyaudio
是不是缺少了索引文件

**Comment by wzpan** [comment]
google 一下就能找打解决方法

**Comment by LJW813120** [comment]
> google一下就能找打解决方法

OK，OK
