### ISSUE TITLE
使用树莓派双麦克阵列麦克风启动失败

### ISSUE THREAD

**Issue by 5high** [wzpan/wukong-robot#48]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装

**操作系统**

Raspbian

**问题描述**

具体说明下问题

********************************************************
*          wukong-robot - 中文语音对话机器人           *
*          (c) 2019 潘伟洲 <m@hahack.com>              *
*     https://github.com/wzpan/wukong-robot.git        *
********************************************************

            如需退出，可以按 Ctrl-4 组合键。

配置文件/root/.wukong/config.yml不存在，要创建吗？(y/n)y
2019-04-05 07:13:06,509 - robot.ASR - INFO - 使用 baidu-asr ASR 引擎
2019-04-05 07:13:06,516 - robot.AI - INFO - 使用 emotibot 对话机器人
2019-04-05 07:13:06,521 - robot.TTS - INFO - 使用 baidu-tts TTS 引擎
2019-04-05 07:13:06,526 - robot.NLU - INFO - 使用 unit NLU 引擎
2019-04-05 07:13:06,572 - robot.plugin_loader - INFO - 插件 Camera 已被禁用
2019-04-05 07:13:06,592 - robot.plugin_loader - INFO - 插件 CleanCache 加载成功 
2019-04-05 07:13:06,713 - robot.plugin_loader - INFO - 插件 Email 加载成功 
2019-04-05 07:13:06,756 - robot.plugin_loader - INFO - 插件 LocalPlayer 加载成功 
2019-04-05 07:13:06,775 - robot.plugin_loader - INFO - 插件 Poem 加载成功 
2019-04-05 07:13:06,783 - robot.Brain - INFO - 已激活插件：['cleancache', 'email', 'LocalPlayer', 'poem']
2019-04-05 07:13:07,535 - robot.TTS - INFO - baidu-tts 语音合成成功，合成路径：/tmp/tmpmijbasga.mp3
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm_dmix.c:990:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dsnoop.c:556:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
ALSA lib pcm_dmix.c:990:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dsnoop.c:556:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

**Comment by wzpan** [comment]
你应该怀疑的是 respeaker 的驱动问题。目前一种可能的问题是 respeaker 的驱动在新的树莓派系统上会有兼容问题。

群里有用户遇到类似的问题，通过重装系统+respeaker驱动解决。

**Comment by 5high** [comment]
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock


Jack Server是什么服务？

**Comment by wzpan** [comment]
只是不影响功能的信息

https://stackoverflow.com/questions/4672457/pyaudio-trying-to-use-jack

**Comment by 5high** [comment]
root@raspberrypi:/home/pi/wukong-robot/static# jack_control start
Traceback (most recent call last):
  File "/usr/bin/jack_control", line 399, in <module>
    main()
  File "/usr/bin/jack_control", line 158, in main
    bus = dbus.SessionBus()
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
root@raspberrypi:/home/pi/wukong-robot/static#


强行启动会这样报错

我现在可以听到声音，但是悟空还是收不到麦克风的声音。

**Comment by 5high** [comment]
用命令行可以正常用Areclord录音并成功使用aplay播放，就是python3启动悟空听不到我讲话。

**Comment by wzpan** [comment]
听不到你说话也可能是唤醒词没训练好

**Comment by 5high** [comment]
直接改了wukong_pi唤醒次，唤醒了一次，第二次识别语音卡死，现在重启没声音了，真是捉急。

**Comment by wzpan** [comment]
@Pengree 最近也遇到这个问题了。初步可以判定是 pulseaudio 与 Respeaker 的兼容性问题。

解决方法：

1. 重刷树莓派镜像；
2. 先安装好 pulseaudio ：

``` sh
sudo apt-get install python-pyaudio python3-pyaudio sox pulseaudio libsox-fmt-all ffmpeg
```

3. 安装 respeaker 的驱动；
4. 安装 wukong-robot 。

这样就可以正常使用。

**Comment by faweiz** [comment]
Make a new folder name "pulse_config_2mic" and copy files from …_4mic and upload to the pi then follow instruction in the gitthub page
(https://github.com/wzpan/wukong-robot/assets/6694983/18151fad-a949-4ac3-bc35-05a0241e3065)
