### ISSUE TITLE
Raspberry Pi 3B+使用WM8960 Audio HAT默认声卡问题

### ISSUE THREAD

**Issue by zhiwehu** [wzpan/wukong-robot#49]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装

**操作系统**

Raspbian Stretch 
**问题描述**

我使用的是微雪电子的WM8960 Audio HAT，按他们提供的文档，录音和播放使用arecord和aplay，加上-D设置设备为hd1,0没有问题，但如果不加-D的话，则无法录间和播放，我试过你文档上的方法设置默认声卡的方法以及其他的方法都不奏效，这些方法包括：
1. 设置~/.asoundrc文件
```pcm.!default {
        type asym
        playback.pcm {
            type plug
            slave.pcm "hw:1,0"
        }
        capture.pcm {
            type plug
            slave.pcm "hw:1,0"
        }
}

ctl.!default {
        type hw
        card 1
}```

2. 设置/etc/asound.conf
```
pcm.!default  {
 type hw card 1
}
ctl.!default {
 type hw card 1
}
```

3. 修改/usr/share/alsa/alsa.conf
将
```
defaults.ctl.card 0
defaults.pcm.card 0
```
修改成
```
defaults.ctl.card 1
defaults.pcm.card 1
```
以上方法都无法成功，在linux上直接使用`rec`和`play`无法录音和播放。

请求帮助，非常感谢。

**Comment by zhiwehu** [comment]
已经解决，将默认声卡放到alsa-blacklist中去禁用了，参考https://www.instructables.com/id/Disable-the-Built-in-Sound-Card-of-Raspberry-Pi/

**Comment by Myeeoo** [comment]
链接打不开

**Comment by nehcrong** [comment]
> 已经解决，将默认声卡放到alsa-blacklist中去禁用了，参考https://www.instructables.com/id/Disable-the-Built-in-Sound-Card-of-Raspberry-Pi/

你好，感谢你的问题记录，我遇到了和你一样的问题，在尝试关闭默认声卡后，使用aplay播放是有声音，但使用arecord录音还是必须要指定声卡hw:0,0
我怀疑还是由于pulseaudio引起的，将pulseaudio卸载后，录音没问题了，但同时也没法继续使用wukong，重装pulseaudio还是会问题重现，希望会有更好的解决办法！

**Comment by KeithMorning** [comment]
https://wiki.archlinux.org/index.php/PulseAudio/Troubleshooting#Microphone_not_detected_by_PulseAudio
通过配置 pulseaudio 值搞定，应该是 pulseaudio 没有检测到
