### ISSUE TITLE
小白，不知道哪出错了

### ISSUE THREAD

**Issue by nameluck** [wzpan/wukong-robot#5]
Traceback (most recent call last):
  File "wukong.py", line 4, in <module>
    from robot.updater import Updater
ImportError: No module named 'robot.updater'

**Comment by wzpan** [comment]
你下的是最新版本吗？检查下robot目录下是updater.py还是Updater.py。应该是 updater.py

**Comment by wzpan** [comment]
问题应该解决，先关了。

**Comment by nameluck** [comment]
谢谢您，问题解决了
