### ISSUE TITLE
PS3 Eye

### ISSUE THREAD

**Issue by abanger** [wzpan/wukong-robot#50]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装

**操作系统**

Raspbian Stretch

**问题描述**

PS3 Eye 安装后，motion可看视频，
“[camera] 拍照失败，请检查相机是否连接正确”
INFO:robot.Conversation:命中缓存，播放缓存语音
mmal: Cannot read camera info, keeping the defaults for OV5647
mmal: mmal_vc_component_create: failed to create component 'vc.ril.camera' (1:ENOMEM)
mmal: mmal_component_create_core: could not create component 'vc.ril.camera' (1)
mmal: Failed to create camera component
mmal: main: Failed to create camera component
mmal: Camera is not detected. Please check carefully the camera module is installed correctly

**Comment by abanger** [comment]
命令行：arecord -c 1 -r 16000 -f S16_LE -D plughw:1,0 test.wav
可以录音

**Comment by wzpan** [comment]
配置camera了吗？贴一下你的config.yml里camera的配置。

**Comment by Jesse54211** [comment]
安装这个
sudo apt-get install fswebcam

**Comment by abanger** [comment]
> camera

配置过。上面是日志文件，系统无法连接上camera。

**Comment by abanger** [comment]
> 安装这个
> sudo apt-get install fswebcam

谢谢，安装过。

安装motion，通过motion可以看到视频了。

**Comment by abanger** [comment]
强制为usb接口，分辨率改为640x480，可以拍照。
            usb_camera = True
            if usb_camera:
                #command = "fswebcam --no-banner -r 1024x765 -q -d %s" % (device)
                command = "fswebcam --no-banner -r 640x480 -q -d %s" % (device)
