### ISSUE TITLE
问答无声音，开机有问候音，第一次唤醒有beep音，后续就没有声音了。

### ISSUE THREAD

**Issue by 5high** [wzpan/wukong-robot#51]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装

**操作系统**

Raspbian Stretch

**问题描述**

日志正常显示问答内容，麦克风正常，语音识别正常，只是喇叭无声音。

2019-04-10 09:47:09,059 - snowboy - INFO - Keyword 1 detected at time: 2019-04-10 09:47:09
2019-04-10 09:47:09,084 - __main__ - INFO - 开始录音
2019-04-10 09:47:13,667 - robot.Conversation - INFO - 结束录音
2019-04-10 09:47:16,627 - robot.ASR - INFO - baidu-asr 语音识别到了：['你好吗？']
2019-04-10 09:47:18,823 - robot.AI - INFO - emotibot 回答：你好吗？我很好！你有没有觉得像电影《情书》的情节~
2019-04-10 09:47:19,358 - robot.TTS - INFO - baidu-tts 语音合成成功，合成路径：/tmp/tmp4im8isy1.mp3

进程里出现一堆play命令
pi         722   651  0 09:39 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/temp/ed0b13acab092d00d8af1bd781caccfb.mp3
pi         726   651  0 09:40 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_hi.wav
pi         730   651  0 09:40 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_lo.wav
pi         735   651  0 09:40 pts/1    00:00:00 play -v 1 /tmp/tmpm8sqejau.mp3
pi         739   651  0 09:40 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_hi.wav
pi         746   651  0 09:40 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_lo.wav
root       748   433  0 09:40 ?        00:00:00 sshd: pi [priv]
pi         756   651  0 09:40 pts/1    00:00:00 play -v 1 /tmp/tmp_8_b0onm.mp3
pi         762   748  0 09:40 ?        00:00:00 sshd: pi@pts/2
pi         766   762  0 09:40 pts/2    00:00:01 -bash
pi         773   651  0 09:40 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_hi.wav
pi         796   651  0 09:40 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_lo.wav
pi         801   651  0 09:40 pts/1    00:00:00 play -v 1 /tmp/tmpooe1v9hj.mp3
pi         806   651  0 09:40 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_hi.wav
pi         812   651  0 09:40 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_lo.wav
pi         817   651  0 09:40 pts/1    00:00:00 play -v 1 /tmp/tmpz6vl1sxj.mp3
pi         821   651  0 09:40 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_hi.wav
pi         829   651  0 09:40 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_lo.wav
pi         835   651  0 09:40 pts/1    00:00:00 play -v 1 /tmp/tmpaeu30im5.mp3
pi         839   651  0 09:40 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_hi.wav
pi         847   651  0 09:41 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_lo.wav
pi         852   651  0 09:41 pts/1    00:00:00 play -v 1 /tmp/tmpty2fy0ft.mp3
pi         856   651  0 09:41 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_hi.wav
pi         866   651  0 09:41 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_lo.wav
pi         871   651  0 09:41 pts/1    00:00:00 play -v 1 /tmp/tmperjxl98o.mp3
pi         875   651  0 09:41 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_hi.wav
pi         882   651  0 09:41 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_lo.wav
pi         887   651  0 09:41 pts/1    00:00:00 play -v 1 /tmp/tmpiqtmj2t_.mp3
pi         891   651  0 09:41 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_hi.wav
pi         897   651  0 09:41 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_lo.wav
pi         902   651  0 09:41 pts/1    00:00:00 play -v 1 /tmp/tmplnlr5s8h.mp3
pi         906   651  0 09:41 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_hi.wav
pi         912   651  0 09:41 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_lo.wav
pi         917   651  0 09:41 pts/1    00:00:00 play -v 1 /tmp/tmp72djtvkh.mp3
pi         921   651  0 09:41 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_hi.wav
pi         927   651  0 09:41 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_lo.wav
pi         932   651  0 09:41 pts/1    00:00:00 play -v 1 /tmp/tmpco8ax2gc.mp3
pi         936   651  0 09:41 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_hi.wav
pi         942   651  0 09:41 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_lo.wav
pi         948   651  0 09:42 pts/1    00:00:00 play -v 1 /tmp/tmptm9nklya.mp3
pi         952   651  0 09:42 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_hi.wav
pi         958   651  0 09:42 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_lo.wav
pi         963   651  0 09:42 pts/1    00:00:00 play -v 1 /tmp/tmpozu1etqv.mp3
pi         967   651  0 09:42 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_hi.wav
pi         973   651  0 09:42 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_lo.wav
pi         978   651  0 09:42 pts/1    00:00:00 play -v 1 /tmp/tmpwksz0kxl.mp3
pi         982   651  0 09:42 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_hi.wav
pi         988   651  0 09:42 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_lo.wav
pi         993   651  0 09:42 pts/1    00:00:00 play -v 1 /tmp/tmp0ka1bp3f.mp3
pi         997   651  0 09:42 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_hi.wav
pi        1003   651  0 09:42 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_lo.wav
pi        1008   651  0 09:42 pts/1    00:00:00 play -v 1 /tmp/tmpdu1cmh3o.mp3
pi        1014   651  0 09:43 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_hi.wav
pi        1018   651  0 09:44 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_lo.wav
pi        1023   651  0 09:44 pts/1    00:00:00 play -v 1 /tmp/tmp6vvo3e20.mp3
pi        1027   651  0 09:44 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_hi.wav
pi        1033   651  0 09:44 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_lo.wav
root      1034     2  0 09:44 ?        00:00:01 [kworker/u2:3]
pi        1039   651  0 09:44 pts/1    00:00:00 play -v 1 /tmp/tmpkeq37pkz.mp3
pi        1043   651  0 09:44 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_hi.wav
pi        1049   651  0 09:44 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_lo.wav
pi        1054   651  0 09:44 pts/1    00:00:00 play -v 1 /tmp/tmp97b6gqjo.mp3
pi        1058   651  0 09:44 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_hi.wav
pi        1065   651  0 09:44 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_lo.wav
pi        1071   651  0 09:44 pts/1    00:00:00 play -v 1 /tmp/tmp11w0emtn.mp3
pi        1076   651  0 09:44 pts/1    00:00:00 play -v 1 /home/pi/wukong-robot/static/beep_hi.wav
pi        1089   651  0 09:44 pts/1    00:00:00 play -v 1 /tmp/tmpntzmep9u.mp3
**复现步骤**

具体描述下复现步骤

**Comment by 5high** [comment]
然后我尝试杀掉python3进程，堵着的那些play mp3全部都释放出来了，音箱里能听到是之前堵塞的声音。

**Comment by 5high** [comment]
syslog 里会出现海量日志，都是同样的内容。杀掉python3 进程日志消失。

Apr 10 10:40:40 raspberrypi pulseaudio[663]: [alsa-sink-bcm2835-i2s-wm8960-hifi wm8960-hifi-0] alsa-sink.c: Resume failed, couldn't restore original sample settings.
Apr 10 10:40:40 raspberrypi pulseaudio[663]: [alsa-sink-bcm2835-i2s-wm8960-hifi wm8960-hifi-0] alsa-sink.c: Resume failed, couldn't restore original sample settings.
Apr 10 10:40:40 raspberrypi pulseaudio[663]: [alsa-sink-bcm2835-i2s-wm8960-hifi wm8960-hifi-0] alsa-sink.c: Resume failed, couldn't restore original sample settings.
Apr 10 10:40:40 raspberrypi pulseaudio[663]: [alsa-sink-bcm2835-i2s-wm8960-hifi wm8960-hifi-0] alsa-sink.c: Resume failed, couldn't restore original sample settings.

**Comment by wzpan** [comment]
看起来与 #47 是同个问题。看下是否能类似解决？

**Comment by 5high** [comment]
他把录音和播放设备分开了，目前我的Zero只有一个双麦克风HAT，分离好像不适合我。

**Comment by 5high** [comment]
Your branch is up-to-date with 'origin/respeaker'

我是这个分支，你之前的bug修复是否涉及了这个分支

**Comment by wzpan** [comment]
我没有做任何bugfix。你是不是可以试试把 3.5mm 插到树莓派本身的口？

**Comment by 5high** [comment]
我是树莓派zero没有3.5mm接口

**Comment by 5high** [comment]
换了树莓派2B 结果一样

**Comment by 5high** [comment]
换了树莓派B2后用板子上的耳机口，外加麦克风扩展板收音，故障消失。

分离麦克和喇叭之后一切工作正常，请问这个是软件bug还是pulseaudio的问题呢？

**Comment by wzpan** [comment]
@5high 我怀疑是 Zero 的问题。Zero 的处理能力毕竟还是太弱了。

**Comment by horwinhee** [comment]
> 换了树莓派B2后用板子上的耳机口，外加麦克风扩展板收音，故障消失。
> 
> 分离麦克和喇叭之后一切工作正常，请问这个是软件bug还是pulseaudio的问题呢？

请问你是怎么将麦克跟喇叭分开配置的，我用的3B+，用了音频拓展板，出现了相同的问题，但是我后面将设备分离开来，树莓派重启之后就失效了，现在一点声音都没有了

**Comment by 15819996676** [comment]
usb麦克风不能用于snowboy 录音，其他时候都正常录音，就是启动悟空语音后录音失效，怎么回事

**Comment by 15819996676** [comment]
使用rec录音没声音，估计录不上，但是使用arecord既可以录音正常为啥？是麦克风问题马？

**Comment by 15819996676** [comment]
还有启动悟空语音后终端不显示信息，比如加载什么插件等信息，然后麦克风不能录音，也就不能唤醒
