### ISSUE TITLE
网页后端 访问呢昂500: Internal Server Error

### ISSUE THREAD

**Issue by 5high** [wzpan/wukong-robot#54]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装

**操作系统**

Raspbian Stretch

**问题描述**

网页打开后显示

500: Internal Server Error

日志里没有任何错误信息，请问哪里可以debug这部分。

**复现步骤**

具体描述下复现步骤

**Comment by wzpan** [comment]
确认下有没有端口占用。

``` sh
lsof -i:5000
```

telnet 一下试试：

``` sh
```
