### ISSUE TITLE
关于树莓派系统更新后部分交互功能出错的问题

### ISSUE THREAD

**Issue by Conrad-hui** [wzpan/wukong-robot#56]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装/docker安装

**操作系统**

（例如 Raspbian Stretch、Ubuntu 16.04）

**问题描述**

具体说明下问题

**复现步骤**

具体描述下复现步骤

**Comment by Conrad-hui** [comment]
我之前使用过叮当，之前也有过同样的问题，当首次安装运行时没什么问题，当运行update、upgrade更新系统后，例如百度地图路线规划插件，当发送路线规划指令后，开始交互，悟空说去哪里，后面开始聆听的提示音播放后还来不及回复立刻就会播放结束聆听的提示音，悟空回复已取消。不知道是哪里有bug，这两个版本都遇到过这种问题。

**Comment by wzpan** [comment]
应该跟你的麦克风驱动有关。最好重装下驱动。

**Comment by Conrad-hui** [comment]
我买的这个USB麦克风是免驱动的，该怎么解决？

**Comment by wzpan** [comment]
太差的麦克风有可能会导致录音提前结束，因为收音太小了，被snowboy判断为静音了。

试试调整下配置文件中的 `silent_threshold` ，避免被提前判断成静音。

**Comment by Conrad-hui** [comment]
好的，多谢解答

**Comment by Conrad-hui** [comment]
INFO:snowboy:Keyword 1 detected at time: 2019-04-18 11:36:01
INFO:__main__:开始录音
INFO:robot.Conversation:结束录音
INFO:robot.ASR:baidu-asr 语音识别到了：['路线规划，']
INFO:robot.Brain:'路线规划，' 命中技能 direction
INFO:robot.Conversation:命中缓存，播放缓存语音
Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1736
Expression 'AlsaOpen( &alsaApi->baseHostApiRep, params, streamDir, &self->pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1904
Expression 'PaAlsaStreamComponent_Initialize( &self->capture, alsaApi, inParams, StreamDirection_In, NULL != callback )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2171
Expression 'PaAlsaStream_Initialize( stream, alsaHostApi, inputParameters, outputParameters, sampleRate, framesPerBuffer, callback, streamFlags, userData )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2840
CRITICAL:snowboy:[Errno -9985] Device unavailable
INFO:robot.TTS:baidu-tts 语音合成成功，合成路径：/tmp/tmpmt_ymo71.mp3
这是出错信息，之前没注意到。不清楚为什么更新系统之前没问题，更新之后会有问题。

**Comment by wzpan** [comment]
pulseaudio 装了没？另外可以先用搜索引擎搜一下看有没有类似解答，这个问题和 wukong-robot 本身是无关的，和麦克风配置可能有关。

**Comment by Conrad-hui** [comment]
好的，我再找找解决方案。pulseaudio已经安装了，按https://blog.csdn.net/qq_23729557/article/details/78968009博客方法配置了，但没起作用，我再找找别的方法。感谢解答。
