### ISSUE TITLE
'_xsrf' argument missing from POST，后台无法登录

### ISSUE THREAD

**Issue by abanger** [wzpan/wukong-robot#59]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装

**操作系统**

（例如 Raspbian）

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

'_xsrf' argument missing from POST，后台无法登录

**复现步骤**
刚根据提示升级为最新版本
后台登录时
WARNING:tornado.general:403 POST /login (192.168.137.1): '_xsrf' argument missing from POST
WARNING:tornado.access:403 POST /login (192.168.137.1) 18.47ms
WARNING:tornado.access:404 GET /favicon.ico (192.168.137.1) 8.63ms

**Comment by wzpan** [comment]
当前 VERSION 是几呢？再次升级一下试试：

``` bash
python3 wukong.py update
```

**Comment by abanger** [comment]
> 当前 VERSION 是几呢？再次升级一下试试：
> 
> ```shell
> python3 wukong.py update
> ```

已经是update到最新版本了。

**Comment by wzpan** [comment]
我昨晚已经移除掉了 xsrf_cookie ，请再次更新。

**Comment by abanger** [comment]
> 我昨晚已经移除掉了 xsrf_cookie ，请再次更新。

谢谢，可以了。
