### ISSUE TITLE
拍照成功，相应路径没有照片

### ISSUE THREAD

**Issue by xushuaibing** [wzpan/wukong-robot#60]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装/docker安装

**操作系统**

（例如 Raspbian Stretch、Ubuntu 16.04）

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

具体说明下问题
拍照成功，相应路径没有照片，文件夹权限已改为777

**Comment by wzpan** [comment]
首先确认下你本地确实有这个目录。

另外尝试自己用命令行拍照，确认可以拍。

* 树莓派摄像头：`raspistill -o test.png`
* USB摄像头：`fswebcam --no-banner -d 设备号 test.png`
* mac摄像头:  `imagesnap test.png`

再不行，贴 log 。

**Comment by xushuaibing** [comment]
应该是我设备问题 ，用cheese 没有问题，用fswebcam有问题
--- Opening /dev/video0...
Trying source module v4l2...
/dev/video0 opened.
No input was specified, using the first.
Unable to query input 0.
VIDIOC_ENUMINPUT: Inappropriate ioctl for device

**Comment by wzpan** [comment]
@xushuaibing 配置好 camera 插件的 device 没？
