### ISSUE TITLE
树莓派-唤醒后回答没有声音

### ISSUE THREAD

**Issue by alexwale** [wzpan/wukong-robot#62]
**确认已寻找过答案**

安装完成，可以正常唤醒，连续对话。试了一些技能都OK。
问题是回答没有声音。
开启悟空后，播放本地或者网页音乐都没有声音。退出悟空，播放正常。
于是我反其道行之。开着音乐播放器，把播放器静音，然后让歌曲一直播放。
然后唤醒。对话。问答。正常。也有声音。
我感觉这是一个BUG

**Comment by wzpan** [comment]
装了 libsox-fmt-all 没？

**Comment by alexwale** [comment]
安装过了哦  最新版

**Comment by wzpan** [comment]
是什么硬件呢？
