### ISSUE TITLE
声音录取和播放成功，启动报错。

### ISSUE THREAD

**Issue by HerculeMo** [wzpan/wukong-robot#63]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装/docker安装

**操作系统**
raspberrypi Debian system
（例如 Raspbian Stretch、Ubuntu 16.04）

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

具体说明下问题
命令行输入 python3 wukong.py
出现以下信息：
Could not import the PyAudio C module '_portaudio'.
Traceback (most recent call last):
  File "wukong.py", line 2, in <module>
    from snowboy import snowboydecoder
  File "/home/pi/wukong-robot/snowboy/snowboydecoder.py", line 4, in <module>
    import pyaudio
  File "/home/pi/.local/lib/python3.5/site-packages/pyaudio.py", line 116, in <module>
    import _portaudio as pa
ImportError: /home/pi/.local/lib/python3.5/site-packages/_portaudio.cpython-35m-arm-linux-gnueabihf.so: undefined symbol: Pa_GetStreamReadAvailable

参考https://stackoverflow.com/questions/36681836/pyaudio-could-not-import-portaudio/
portaudio 是手工编译0.2.11版本，添加
sudo ldconfig
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/your/custom/path/" >> ~/.bashrc
错误依然是一样的存在。
请教大师，帮忙分析下原因，多谢。

**Comment by wzpan** [comment]
```
sudo ldconfig
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/your/custom/path/" >> ~/.bashrc
```

这里 `echo` 完后，有 `source` 一下让 .bashrc 生效吗？因为这其实和 wukong-robot 本身使用无关，我也没办法提供更多帮助。
