### ISSUE TITLE
运行出现错误如下，但程序没有退出，卡在一个地方

### ISSUE THREAD

**Issue by cyndi905** [wzpan/wukong-robot#64]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**
手动安装

**操作系统**
树莓派系统raspbian

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

具体说明下问题
命令行输入 python3 wukong.py
然后出现下面信息
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 924
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 924
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
程序卡在这里，没有退出，也没有其他提示

**Comment by wzpan** [comment]
这不是卡，也不是错误。这是在等待你唤醒。如果唤醒不了，请检查你的麦克风配置。

**Comment by wzpan** [comment]
说明不是卡。因为日志不可能一直输出，你要有指令才输出。

> 任意改了下悟空的配置文件config.yml，然后保存，程序立马就会有其他信息输出

那是因为我加了配置文件的修改检测，一旦你修改了配置文件就会自动reload整个配置文件，所以会打印相应的日志。并不是因为这些日志被卡住没有打印直到你改了配置文件才“不卡”。
