### ISSUE TITLE
debian9无法运行

### ISSUE THREAD

**Issue by TSL-Johnson** [wzpan/wukong-robot#65]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装

**操作系统**

debian9

**离线唤醒相关**

我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**
启动有“师傅你好，试试用唤醒词叫醒我吧”
日志：
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
唤醒无反应
后台管理发送指令无反应，会有如下日志：
WARNING:tornado.access:404 GET /favicon.ico (192.168.123.189) 5.91ms
WARNING:tornado.access:404 GET /favicon.ico (192.168.123.189) 6.02ms

**Comment by wzpan** [comment]
同 #64
