### ISSUE TITLE
运行出错在python3: can't open file 'wukong.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by FFXW0720** [wzpan/wukong-robot#68]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装

**操作系统**

Raspbian

**启动相关**

**问题描述**

命令行输入 python3 wukong.py

结果显示python3: can't open file 'wukong.py': [Errno 2] No such file or directory

**Comment by wzpan** [comment]
你应该先 cd 进入 wukong-robot 所在的目录。

**Comment by FFXW0720** [comment]
我本来就进入了，就是不行

**Comment by wzpan** [comment]
你那个目录究竟有没有这个文件呢

**Comment by FFXW0720** [comment]
有的，我看过

**Comment by wzpan** [comment]
@FFXW0720 请先 cd 进 wukong-robot ，然后 ls 一下，再尝试执行 `python3 wukong.py` ，把整个终端的操作截个屏我看下。

**Comment by FFXW0720** [comment]
我最近没什么时间，你加一下我QQ2822603942，我有时间就发给你进展，不然这个issue会过期

**Comment by FFXW0720** [comment]
问题解决了谢谢

**Comment by FutabaRioo-o** [comment]
同求如何解决的
