### ISSUE TITLE
无法唤醒悟空

### ISSUE THREAD

**Issue by nameluck** [wzpan/wukong-robot#7]
********************************************************
*          wukong-robot - 中文语音对话机器人           *
*          (c) 2019 潘伟洲 <m@hahack.com>              *
*     https://github.com/wzpan/wukong-robot.git        *
********************************************************
active_mode not specified in profile, defaulting to 'False'
statistic not specified in profile, defaulting to 'True'
WARNING:robot.config:silent_threshold not specified in profile, defaulting to '15'
WARNING:robot.config:recording_timeout not specified in profile, defaulting to '5'
connect(2) call to /tmp/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
WARNING:robot.config:active_mode not specified in profile, defaulting to 'False'
对麦克风说孙悟空没有反应，是需要去snowboy上训练我的声学模型么？
我没找到默认创建的用户目录 ，因为第一次运行的时候询问是否要创建，我点击了创建，但是没有留意该目录，现在想配置该用户目录下的yml文件，找不到了。

**Comment by wzpan** [comment]
> 对麦克风说孙悟空没有反应，是需要去snowboy上训练我的声学模型么？

是的，建议自己训练。

> 我没找到默认创建的用户目录 ，因为第一次运行的时候询问是否要创建，我点击了创建，但是没有留意该目录，现在想配置该用户目录下的yml文件，找不到了。

目录是建在 `.wukong` 下，*nix 系统会将带点的目录隐藏。要打开该目录，有几种方法：

* 如果是 Mac 系统，可以用 `open` 命令：

``` bash
open ~/.wukong
```

* 如果是 Linux：

  - 方案1：大多数的文件管理器多支持 `Ctrl-h` 组合键切换显示/隐藏目录；
  - 方案2：使用如下命令：

  ``` bash
  xdg-open ~/.wukong
  ```

**Comment by nameluck** [comment]
那warning里面为啥有一个尝试连接服务器失败呢，我用的是树莓派，显示隐藏目录，进入了.wukong，里面是空的

**Comment by wzpan** [comment]
那个问题不用管。Linux 的 alsa 的警告，但没任何影响。

你确定按了 y 键？并且是同一个用户？

**Comment by nameluck** [comment]
pi@raspberrypi:~ $ cd wukong
pi@raspberrypi:~/wukong $ ls -a
.  ..  contrib  swig-3.0.10  swig-3.0.10.tar.gz  wukong-robot
pi@raspberrypi:~/wukong $ cd wukong-robot
pi@raspberrypi:~/wukong/wukong-robot $ ls -a
.       .git        plugins           robot    static   .wukong
..      .gitignore  README.md         server   temp     wukong.py
docker  LICENSE     requirements.txt  snowboy  VERSION
pi@raspberrypi:~/wukong/wukong-robot $ cd .wukong
pi@raspberrypi:~/wukong/wukong-robot/.wukong $ ls -a
.  ..
pi@raspberrypi:~/wukong/wukong-robot/.wukong $
这不就是空的么 ，我当时按y键了，即使我没按y键，没有创建那个文件，我第二次进入，他不应该还会提示我创建那个用户文件么?可是并没有提示啊，

**Comment by nameluck** [comment]
`pi@raspberrypi:~ $ cd wukong
pi@raspberrypi:/wukong $ ls -a
. .. contrib swig-3.0.10 swig-3.0.10.tar.gz wukong-robot
pi@raspberrypi:/wukong $ cd wukong-robot
pi@raspberrypi:/wukong/wukong-robot $ ls -a
. .git plugins robot static .wukong
.. .gitignore README.md server temp wukong.py
docker LICENSE requirements.txt snowboy VERSION
pi@raspberrypi:/wukong/wukong-robot $ cd .wukong
pi@raspberrypi:/wukong/wukong-robot/.wukong $ ls -a
. ..
pi@raspberrypi:/wukong/wukong-robot/.wukong $`
pi@raspberrypi:~ $ cd wukong
pi@raspberrypi:/wukong $ ls -a
. .. contrib swig-3.0.10 swig-3.0.10.tar.gz wukong-robot
pi@raspberrypi:/wukong $ cd wukong-robot
pi@raspberrypi:/wukong/wukong-robot $ ls -a
. .git plugins robot static .wukong
.. .gitignore README.md server temp wukong.py
docker LICENSE requirements.txt snowboy VERSION
pi@raspberrypi:/wukong/wukong-robot $ cd .wukong
pi@raspberrypi:/wukong/wukong-robot/.wukong $ ls -a
. ..
pi@raspberrypi:/wukong/wukong-robot/.wukong $

**Comment by nameluck** [comment]
pi@raspberrypi:~ $ cd wukong
pi@raspberrypi:/wukong $ ls -a
. .. contrib swig-3.0.10 swig-3.0.10.tar.gz wukong-robot
pi@raspberrypi:/wukong $ cd wukong-robot
pi@raspberrypi:/wukong/wukong-robot $ ls -a
. .git plugins robot static .wukong
.. .gitignore README.md server temp wukong.py
docker LICENSE requirements.txt snowboy VERSION
pi@raspberrypi:/wukong/wukong-robot $ cd .wukong
pi@raspberrypi:/wukong/wukong-robot/.wukong $ ls -a
. ..
pi@raspberrypi:/wukong/wukong-robot/.wukong $
这不就是空的么，即使我第一次没按y键的话，没有创建那个用户文件，第二次进入不应该还会提示我创建么？可是没有提示啊

**Comment by wzpan** [comment]
为什么你看的是 wukong-robot 里的 .wukong？我并没有设计这个目录的存在。

~/.wukong

**Comment by nameluck** [comment]
嗷嗷 不好意思， 我把目录结构看错了，找到了，谢谢您。
`self._conversation.say('{} 你好！试试对我喊唤醒词叫醒我吧'.format(config.get('first_name', '主人')), True)`
我看wukong.py里面有这句代码，都已经出现了这段
********************************************************
*          wukong-robot - 中文语音对话机器人           *
*          (c) 2019 潘伟洲 <m@hahack.com>              *
*     https://github.com/wzpan/wukong-robot.git        *
********************************************************

            如需退出，可以按 Ctrl-4 组合键。
不应该，语音播报，你好试试对我喊唤醒词叫醒我吧么？我的音箱测试过有声音

**Comment by nameluck** [comment]
可是并没有语音播报呀

**Comment by nameluck** [comment]
嗷嗷  谢谢您，我目录结构看错了
