### ISSUE TITLE
邮件插件出故障

### ISSUE THREAD

**Issue by Hhhhhheart** [wzpan/wukong-robot#70]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

一键脚本安装

**操作系统**

Raspbian

**离线唤醒相关**

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

使用Email插件的时候，语音播报出“抱歉，插件Email出故障了，晚点再试试吧”
我已经设置允许第三方客户端收发邮件，已在 ~/.wukong/config.xml 中完成了邮箱的配置，写的也是授权码

**Comment by Hhhhhheart** [comment]
![image](https://user-images.githubusercontent.com/49425804/59157844-6d279d00-8ae4-11e9-9289-066df4e4bd24.png)

**Comment by wzpan** [comment]
用的是什么邮箱呢？建议使用网易163邮箱。

**Comment by Hhhhhheart** [comment]
我用的是网易136邮箱，授权什么的都弄好了，但是还是不行
