### ISSUE TITLE
会自动录音

### ISSUE THREAD

**Issue by Hhhhhheart** [wzpan/wukong-robot#71]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

一键安装

**操作系统**

Raspbian 

**离线唤醒相关**

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

开启wukong后，还没唤醒，系统就自动开始录音，都是一些没说过的，而且与语音输出还没完，就又自动开始录音，后来把麦克风拔掉重启发现还是会继续录音，竟然还能识别出一些字

**复现步骤**

具体描述下复现步骤

**Comment by Hhhhhheart** [comment]
![image](https://user-images.githubusercontent.com/49425804/59221478-eebd1f00-8bf9-11e9-94e0-c8faabc7b255.png)

**Comment by Hhhhhheart** [comment]
这些我都没讲过的话，还是拔掉了麦克风

**Comment by wzpan** [comment]
![image](https://user-images.githubusercontent.com/1631405/60781865-c67ffc00-a176-11e9-81a1-b599c444c05f.png)

识别到唤醒词了。如果不是你唤醒的，说明唤醒词没训练好，误唤醒了。重新训练下。
