### ISSUE TITLE
语音合成播放不完整

### ISSUE THREAD

**Issue by huoniu** [wzpan/wukong-robot#72]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

脚本安装

**操作系统**

Raspbian GNU/Linux 9 (stretch)

**离线唤醒相关**

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

2019-06-20 00:15:46,884 - robot.Brain - INFO - '写诗' 命中技能 poem
2019-06-20 00:15:46,895 - robot.Conversation - INFO - onSay: 曾写诗行几度秋,酸甜苦辣共登楼,谁言此地无春色,我自吟哦乐不休
2019-06-20 00:15:47,387 - robot.TTS - INFO - baidu-tts 语音合成成功，合成路径：/tmp/tmp5xgp40f9.mp3

语音合成播放不完整
下载mp3文件播放,是完整的
但是实际使用中,结尾少2-3秒
包括聊天机器人也是如此
运行环境是树莓派modelB通过脚本自动安装

**Comment by wzpan** [comment]
我看代码应该是没问题的。

![image](https://user-images.githubusercontent.com/1631405/61360390-ef0fa080-a8b0-11e9-8a69-6916fbd299e6.png)

[这里](https://github.com/wzpan/wukong-robot/blob/master/robot/Player.py#L81) 就是等播放进程结束。除非系统或者sox有bug提前结束。你可以试试强制延长多一两秒：在 self.proc.wait() 后加一句 time.sleep(1) 。例如：

```
# -*- coding: utf-8-*-
import time 
...


class SoxPlayer(AbstractSoundPlayer):

    ...

    def run(self):
        cmd = ['play', '-v', str(self.volume), str(self.src)]
        logger.debug('Executing %s', ' '.join(cmd))

        self.proc = subprocess.Popen(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        self.playing = True
        self.proc.wait()
        time.sleep(1)  # 强制再等待一秒确保说完
        self.playing = False
        if self.delete:
            utils.check_and_delete(self.src)
        logger.debug('play completed')
        for onCompleted in self.onCompleteds:
            if onCompleted:                
                onCompleted()
        self.onCompleteds = []
```

另外这个文件开头记得 import time 。
