### ISSUE TITLE
离线唤醒机制初始化失败：[Errno -9997] Invalid sample rate

### ISSUE THREAD

**Issue by kaidoxue** [wzpan/wukong-robot#75]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装

**操作系统**

Raspbian buster

**离线唤醒相关**

已确保 `arecord temp.wav`、`aplay temp.wav` (Linux)已正常工作.（没有带任何其他参数）

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

********************************************************
*          wukong-robot - 中文语音对话机器人           *
*          (c) 2019 潘伟洲 <m@hahack.com>              *
*     https://github.com/wzpan/wukong-robot.git        *
********************************************************

            如需退出，可以按 Ctrl-4 组合键。

Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 924
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 924
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 934
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 934
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 934
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 924
Expression 'paInvalidSampleRate' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2048
Expression 'PaAlsaStreamComponent_InitialConfigure( &self->capture, inParams, self->primeBuffers, hwParamsCapture, &realSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2719
Expression 'PaAlsaStream_Configure( stream, inputParameters, outputParameters, sampleRate, framesPerBuffer, &inputLatency, &outputLatency, &hostBufferSizeMode )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2843
CRITICAL:__main__:离线唤醒机制初始化失败：[Errno -9997] Invalid sample rate

**Comment by wzpan** [comment]
这种看起来就是你的麦克风不支持snowboy要求的采样率了。建议换麦克风。

**Comment by kaidoxue** [comment]
谢谢大神，我买一个PS3 Eye 再试试

**Comment by cgn5566** [comment]
请问楼上这个问题解决了吗？
我也遇到相同的问题了
奇怪的是在shell里运行python3 wukong.py是正常的，可以正常采集和识别语音。
但是设置为开机自启动就会报
CRITICAL:main:离线唤醒机制初始化失败：[Errno -9997] Invalid sample rate
无论采用哪种自启动方式都是相同的结果

**Comment by cgn5566** [comment]
针对大神wzpan的解答小弟有一点疑惑，如果是麦克风的问题，是不是在shell里面运行wukong.py
的时候，就会报这个错误啊？奇怪的是手动在shell里运行时正常的。但是设置开启自启动就不行了

**Comment by cgn5566** [comment]
大神wzpan您好，按照您的教程我重新编译了_snowboydetect.so
现在报错变成了
离线唤醒机制初始化失败：[Errno -9996] Invalid input device (no default output device)
按照您的教程我用ps -auwx | grep wukong查询
只有一个wukong.py进程在跑...

**Comment by wzpan** [comment]
@cgn5566 设置自启动是用什么方法？注意要用和你平时terminal里跑的是用同个用户，如果你是用root来跑，`.asoundrc` 和 `.wukong/config.yml` 是没法共享给 root 的，就会出问题。

**Comment by cgn5566** [comment]
大神wzpan您好，我是采用修改rc.local文件开机自启动脚本的
之前我用rc.local、systemd、supervisor、my.desktop四种方法都尝试过，结果是一样的：离线唤醒机制初始化失败
我没指定用户，我平时登录树莓派的是pi用户（已经重新设置过pi密码了），刚才按照您的提示，我尝试指定pi用户来跑，在rc.local文件里添加了
su pi -c "exec /***/***.sh"这条命令 
但是奇怪的是手动执行sh文件是正常的，但是放到rc.local就无效了，重启后没有任何提示音
请问大神如何使用pi用户来跑啊？

**Comment by wzpan** [comment]
@cgn5566 我用的是 desktop 来跑的。你可以参考我给 dingdang 写的 launcher：https://github.com/dingdang-robot/dingdang-robot/blob/master/launcher/dingdang-launcher-user.sh

**Comment by cgn5566** [comment]
已解决！谢谢大神wzpan指导！：）

**Comment by Kuldeepwadaskar** [comment]
i am facing same issue.
can anyone able to answer it in english

**Comment by CheckCoder** [comment]
> 已解决！谢谢大神wzpan指导！：）

@cgn5566  您好！请问是怎么解决的？

**Comment by whuzx** [comment]
请教大佬，我也遇到类似问题
Expression 'paInvalidSampleRate' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2048
Expression 'PaAlsaStreamComponent_InitialConfigure( &self->capture, inParams, self->primeBuffers, hwParamsCapture, &realSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2719
Expression 'PaAlsaStream_Configure( stream, inputParameters, outputParameters, sampleRate, framesPerBuffer, &inputLatency, &outputLatency, &hostBufferSizeMode )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2843

**Comment by taoliescape** [comment]
我也遇到类似的问题了
Expression 'paInvalidSampleRate' failed in 'src/hostapi/alsa/pa_linux_alsa.c', l                                                                                                             ine: 2048
Expression 'PaAlsaStreamComponent_InitialConfigure( &self->capture, inParams, se                                                                                                             lf->primeBuffers, hwParamsCapture, &realSr )' failed in 'src/hostapi/alsa/pa_lin                                                                                                             ux_alsa.c', line: 2719
Expression 'PaAlsaStream_Configure( stream, inputParameters, outputParameters, s                                                                                                             ampleRate, framesPerBuffer, &inputLatency, &outputLatency, &hostBufferSizeMode )                                                                                                             ' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2843
CRITICAL:__main__:离线唤醒机制初始化失败：[Errno Invalid sample rate] -9997
