### ISSUE TITLE
唤醒后，若不录入语音，会出现NoneType错误导致服务不可用

### ISSUE THREAD

**Issue by shawn2013** [wzpan/wukong-robot#76]
**问题描述**
语音唤醒后，若保持安静，不录入语音，会出现NoneType错误导致服务不可用，需要重启服务

具体说明下问题
INFO:snowboy:Keyword 1 detected at time: 2019-07-19 19:28:42
INFO:__main__:开始录音
INFO:robot.Conversation:结束录音
INFO:robot.ASR:baidu-asr 语音识别出错了: speech quality error.
INFO:robot.TTS:baidu-tts 语音合成成功，合成路径：/tmp/tmp7tyytdxs.mp3
Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1736
Expression 'AlsaOpen( &alsaApi->baseHostApiRep, params, streamDir, &self->pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1904
Expression 'PaAlsaStreamComponent_Initialize( &self->capture, alsaApi, inParams, StreamDirection_In, NULL != callback )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2171
Expression 'PaAlsaStream_Initialize( stream, alsaHostApi, inputParameters, outputParameters, sampleRate, framesPerBuffer, callback, streamFlags, userData )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2840
CRITICAL:snowboy:[Errno -9985] Device unavailable
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/mnt/card/wukong-robot/robot/Player.py", line 88, in run
    onCompleted()
  File "/mnt/card/wukong-robot/robot/Conversation.py", line 152, in <lambda>
    self.say("抱歉，刚刚没听清，能再说一遍吗？", onCompleted=lambda: self.doResponse(self.activeListen()))
  File "/mnt/card/wukong-robot/robot/Conversation.py", line 59, in doResponse
    self.appendHistory(0, query, UUID)
  File "/mnt/card/wukong-robot/robot/Conversation.py", line 125, in appendHistory
    if text.endswith(',') or text.endswith('，'):
AttributeError: 'NoneType' object has no attribute 'endswith'

**Comment by wzpan** [comment]
@shawn2013 这个问题我在周五晚应该修复了。请确认下你当前的版本是否最新？（1.6.8）

可以直接在 wukong-robot 当前的版本里头执行如下命令：

```
cat VERSION
```

**Comment by shawn2013** [comment]
好的，我更新下版本
