### ISSUE TITLE
建议支持多人/多个唤醒词

### ISSUE THREAD

**Issue by shawn2013** [wzpan/wukong-robot#77]
**问题描述**
目前snowboy通用唤醒词是商用的，个人用户下载使用单人唤醒词model，而wukong-robot目前仅支持单个唤醒词model。
能否让wukong-robot支持多个唤醒词，就可以多人唤醒了（使用场景：个人家庭使用wukong-robot时，录入多个家庭成员model，使每个人都可以唤醒）
如果有必要的话，可以把我的fork分支里面的修改整合进来（涉及wukong.py、Conversation.py、snowboydetect.py),
https://github.com/shawn2013/wukong-robot.git

**Comment by wzpan** [comment]
没必要。支持多人会增加唤醒词的误唤醒几率。

更合适的是，家里的某个人先在 snowboy 官网里训练一个唤醒词。然后其他成员往同一个唤醒词里贡献训练样本。同个唤醒词是支持多个人参与训练的。

**Comment by shawnlxc** [comment]
> 没必要。支持多人会增加唤醒词的误唤醒几率。
> 
> 更合适的是，家里的某个人先在 snowboy 官网里训练一个唤醒词。然后其他成员往同一个唤醒词里贡献训练样本。同个唤醒词是支持多个人参与训练的。

如何贡献训练样本？是在snowboy官网训练完一个唤醒词后，翻墙用多个facebook或tweet账号分别贡献吗？
貌似通过public link方式下载的pmdl是personal的。

**Comment by shawn2013** [comment]
> 没必要。支持多人会增加唤醒词的误唤醒几率。
> 
> 更合适的是，家里的某个人先在 snowboy 官网里训练一个唤醒词。然后其他成员往同一个唤醒词里贡献训练样本。同个唤醒词是支持多个人参与训练的。

如何贡献训练样本？是在snowboy官网训练完一个唤醒词后，翻墙用多个facebook或tweet账号分别贡献吗？
貌似通过public link方式下载的pmdl是personal的。

**Comment by wzpan** [comment]
例如，登陆了 snowboy 后，你可以给我的 sunwukong 热词贡献样本，然后再下载。

https://snowboy.kitt.ai/hotword/33338

像下面这种，都是很多人同时贡献样本的（samples 就是样本数）：

![image](https://user-images.githubusercontent.com/1631405/61782558-d109e900-ae38-11e9-8569-cf8b27167f28.png)

**Comment by shawn2013** [comment]
<img width="633" alt="企业微信截图_20190731170238" src="https://user-images.githubusercontent.com/46065644/62199051-65ce9280-b3b5-11e9-9631-fbada948cec7.png">
个人贡献样本后，下载的是个人模型pmdl而不是umdl。
不过多个唤醒词，确实是会提高误唤醒率。

**Comment by wzpan** [comment]
这个由多人贡献了样本的 pmdl 是结合了多人的训练样本的。效果更好一些。

**Comment by shawn2013** [comment]
ok
