### ISSUE TITLE
运行后能听到提示音，但无法捕捉到声音

### ISSUE THREAD

**Issue by YvanYangi** [wzpan/wukong-robot#78]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

一键自动安装

**操作系统**

MacOS运行的VMware，系统镜像为Ubuntu 64位18.10

**离线唤醒相关**

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

具体说明下问题

抱歉打扰，现在我的问题是启动之后，有提示音播放，但是提示音说完之后会弹出一段不知道是哪里的貌似是异常，并且声音无法识别录入。如图：
![image](https://user-images.githubusercontent.com/42790947/61771168-aa8c8380-ae21-11e9-81a3-f426ecb1669d.png)

但是在本地管理平台中（localhost:5000）中，可以正常录音输入并正确得到返回
![image](https://user-images.githubusercontent.com/42790947/61771455-7b2a4680-ae22-11e9-9bb8-95e58b7d1e61.png)
![image](https://user-images.githubusercontent.com/42790947/61771596-cc3a3a80-ae22-11e9-81a7-bfd471c49619.png)

**Comment by wzpan** [comment]
在浏览器里的录音用的是浏览器的系统录音。和 wukong-robot 最常用的唤醒-说指令说走的方式不同。

你必须保证能 arecord 、aplay 才尝试 wukong-robot。

**Comment by YvanYangi** [comment]
谢谢回复。我刚刚又测试

**Comment by YvanYangi** [comment]
谢谢回复

我刚刚测试了一下两个命令好像是正常的，如图

![image](https://user-images.githubusercontent.com/42790947/61785753-eaae2f00-ae3e-11e9-9dd5-abe5dce02d07.png)

**Comment by wzpan** [comment]
arecord temp.wav ，不带参数看看能否录制。必须不带都能
