### ISSUE TITLE
悟空与叮当的区别与优势？

### ISSUE THREAD

**Issue by Hu-Yuan** [wzpan/wukong-robot#79]
您好，之前用过您的叮当项目，想知道新的悟空项目与之前的叮当的区别与优势在哪儿？

**Comment by wzpan** [comment]
可以参考我这篇介绍：https://www.hahack.com/codes/wukong-robot-intro/

**Comment by Hu-Yuan** [comment]
谢谢！感觉我们俩有一些共同之处哈哈，但是条理性没您这么强，也没您做的这么极致。真的佩服哈哈，向您学习！！
