### ISSUE TITLE
建议改一下安装手册手动安装关于更新唤醒词的提示

### ISSUE THREAD

**Issue by Yaque** [wzpan/wukong-robot#80]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装/docker安装

**操作系统**

（例如 Raspbian Stretch、Ubuntu 16.04）

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

关于安装手册上，手动安装的第六步更新唤醒词，里面提到了config.yml文件，这个对于刚刚开始接触的人会有点莫名妙，因为安装安装手册的步骤，其实在.wukong的目录下是不会出现的，反而是需要我们在其它步骤里面去得到它，建议更改一下，或者加一下提示。还有提供的snowboy的树莓派版本在我的3b+上不好使。

**复现步骤**
如果看了一眼项目介绍就去尝试安装，而且之前没有接触过叮当项目的人很可能会遇到。

**Comment by wzpan** [comment]
已做了些调整，你看看现在如何？

**Comment by Yaque** [comment]
我觉得OK，应该不会迷路了。感谢大佬为小白做的贡献。
