### ISSUE TITLE
当wukong.log大于1M, 会即时产生五个文件wukong.log.(1-5),而每个文件的内容都是单独一个模块的专属输出内容，如同整理过一样

### ISSUE THREAD

**Issue by netsun-github** [wzpan/wukong-robot#81]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装/docker安装

**操作系统**

（例如 Raspbian Stretch、Ubuntu 16.04）

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

具体说明下问题

**复现步骤**

具体描述下复现步骤

**Comment by wzpan** [comment]
不出奇呀，我用的是 RotateFileHandler 来输出文件，当文件过大时会自动切片，这样管理端的日志页面读取速度就会快很多。

**Comment by netsun-github** [comment]
可能我想多了，我以为是日志文件超出限制后，原文不动的转为wukong.log.N(N=1-5)，wukong.log重新开始作记录的。但现在经过RotateFileHandler 后，wukong.log的内容就只能出现某单独一个模块的内容，而不是象开始时那样所有模块内容的汇总了。

**Comment by wzpan** [comment]
RotatingFileHandler 并不会分模块的。你应该依然能找到一个 wukong.log ，那个文件存放的是最新的日志。
