### ISSUE TITLE
树莓派上本地音乐插件功能紊乱

### ISSUE THREAD

**Issue by shawn2013** [wzpan/wukong-robot#82]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装/docker安装

**操作系统**

（例如 Raspbian Stretch、Ubuntu 16.04）

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**
树莓派上本地音乐插件功能紊乱，但在ubuntu下运行正常

具体说明下问题
唤醒本地播放功能，然后“大点声”、“小点声”等功能，调大/调小了音量的同时，还会切换到其他歌曲播放，打开debug日志后，发现会出现连续的play->complete->next。从日志上看，是在say(“调大音量”)的过程中，原来play音乐的线程出现了连续多个onComplete。
注：

- 这些音乐文件都是能正常播放的
- ubuntu下没有这个情况
- 环境区别是网络带宽，cpu处理能力不同
这个问题应该是个例，希望楼主能给点定位问题或解决问题的思路，我自己尝试解决

日志如下：
<img width="452" alt="企业微信截图_20190802094322" src="https://user-images.githubusercontent.com/46065644/62338896-c4f2eb00-b50c-11e9-9d3a-fd0d93edd4da.png">

**复现步骤**
较难复现
具体描述下复现步骤

**Comment by wzpan** [comment]
pulseaudio 装了吗？

**Comment by shawn2013** [comment]
> pulseaudio 装了吗？

已安装，能正常唤醒、播放。
