### ISSUE TITLE
请问wukong对麦克风的采样率和位深有没有要求？

### ISSUE THREAD

**Issue by cgn5566** [wzpan/wukong-robot#84]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装/docker安装

**操作系统**

（例如 Raspbian Stretch、Ubuntu 16.04）

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

具体说明下问题
你好，请问wukong对麦克风的采样率和位深有没有要求？我使用过一个采样率为8000的usb麦克风，但是无论如何都唤醒不了wukong，已经排除了唤醒词方面的问题，那个麦克风录制的声音质量很差，是不是需要好一点的麦克风才能成功唤醒悟空啊？

**Comment by wzpan** [comment]
是要好一点的麦克风。
