### ISSUE TITLE
在播放时，语音回答的内容总比显示的文本内容要少，最后几个字语音一直没有读出来。

### ISSUE THREAD

**Issue by Dqaq** [wzpan/wukong-robot#86]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装/docker安装

**操作系统**

（例如 Raspbian Stretch、Ubuntu 16.04）

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

具体说明下问题

**复现步骤**

具体描述下复现步骤

**Comment by wzpan** [comment]
是用的什么 TTS 呢？

**Comment by Dqaq** [comment]
百度和阿里的都试过了，

**Comment by wzpan** [comment]
用的是什么设备？列一下。

**Comment by Dqaq** [comment]
麦克风respeaker,音响3.5mm接口音响，2019-7-10日的树莓派镜像，树莓派3b+和4都试过

**Comment by wzpan** [comment]
我也是同样的设备，除了音响不一样。比较怀疑是你的音响响应速度问题。

**Comment by Dqaq** [comment]
好的，我明天更换音响试下

**Comment by Dqaq** [comment]
但是我后来有插上耳机试过，也是不行。耳机质量还算可以

**Comment by wzpan** [comment]
这个问题我暂时没有答案。我的树莓派系统是 stretch ，没有问题。也许还和版本有关。

**Comment by Dqaq** [comment]
我使用的是raspbian的镜像，并且可能是版本问题，我明天再去试着找下问题。多谢

**Comment by tonytan1701** [comment]
1. 先去/wukong-robot/temp/找出相应的tts语音出来，尝试使用play xx.mp3来播放看看，检查是否有问题。

2. 如果再不行，那就只能Hard code，在/wukong-robot/robot/Player.py的SoxPlayer对象里找到运行play的命令，在播放之前运行"play silence.wav trim 0.0 2.0"的命令，也就是空放一段时间再正式播放。

个人建议：可将空播放做到配置文件里，在HA的一个bluetooth_tts_HA项目里也有蛮多人出现这种情况。

@wzpan 大佬~申请了好几次想加入qq群但都没有理会，之前也在github上打赏过。希望能加入组织！

**Comment by wzpan** [comment]
@tonytan1701 把QQ号发一下哈

**Comment by tonytan1701** [comment]
@wzpan 已发送了到此m@hahack.com邮箱了，在github上直接回复有点不太好。

**Comment by wuxiushi** [comment]
我遇到类似情况，分析结论是 play 这个播放命令无法播放完整，感觉不一定是命令问题，也可能wav文件格式问题。临时解决办法， 在/wukong-robot/robot/Player.py的SoxPlayer对象里找到运行play的命令位置，替换成“aplay”或者“mplayer”都可以。

PS：我替换aplay仅启动时无欢迎声音，用“ mplayer”没有问题。另外此法也不是非常完整，最后一个字声不全。

**Comment by tonytan1701** [comment]
此问题暂时无解，改为mplayer也是一种缓解之计。
之前提供的方案是在Player.py执行完播放后，再播放一段空wav文件（用sox命令生成）

**Comment by wzpan** [comment]
@Dqaq 可以试试最新版本支持的 HanTTS ，生成的是 wav 格式的音频。应该不存在播不了的情况。

**Comment by Dqaq** [comment]
好的，已经更新过了，体验蛮棒的
