### ISSUE TITLE
播放音乐后会被唤醒

### ISSUE THREAD

**Issue by lucian-ma** [wzpan/wukong-robot#87]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装/docker安装
手动安装
**操作系统**
Raspbian
（例如 Raspbian Stretch、Ubuntu 16.04）

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**
播放百度音乐 播放了以后自动会被唤醒然后开始自问自答

具体说明下问题

**Comment by wzpan** [comment]
出现这种问题通常是你的唤醒词误识别率比较高导致。有两种方式可以优化：

1. 重新训练唤醒词，挑一个不容易被唤醒的词。例如 “小爱同学” 。
1. 把敏感度调到一个合适的值，既能唤醒，又不会导致误唤醒。

**Comment by wzpan** [comment]
这里提供了几个解决误唤醒率的技巧：

https://wukong.hahack.com/#/tips?id=_3-%e9%99%8d%e4%bd%8e%e8%af%af%e5%94%a4%e9%86%92
