### ISSUE TITLE
不接入麦克的情况下，悟空也能听到自己的声音

### ISSUE THREAD

**Issue by aylzh** [wzpan/wukong-robot#88]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**
一键安装脚本
**操作系统**
Raspbian Stretch

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**
不接入话筒，用后台网页聊天，悟空能听到并识别自己的声音，并且总是上一句说不完就开始下一句，不知道什么原因，谢谢！
具体说明下问题

**Comment by wzpan** [comment]
后台网页聊天，你用的是不是那个麦克风来录音？那个走的录音方式和唤醒的方式并不一样。另外我不太懂你提单是觉得这是个bug？

**Comment by aylzh** [comment]
谢谢，这不能算是bug，我只是不太理解这种情况是怎么发生的，我在管理页面使用的文字聊天，打字上去的，并没有接入麦克，也没有使用后台的那个录音按钮。

**Comment by aylzh** [comment]
我找到答案了，和 #71问题相同，谢谢！
