### ISSUE TITLE
第三方插件不会被加载，不知道什么原因。

### ISSUE THREAD

**Issue by aylzh** [wzpan/wukong-robot#89]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**
一键安装脚本
**操作系统**
Raspbian Stretch

**问题描述**
在树莓派3b+上安装的树莓派Raspbian Stretch系统，启动后可以加载官方插件，但是用户贡献插件加载不了，已经按照安装说明git下来了，目录里也存在插件的文件。切换到月牙版和master都不能加载，不知道哪里出问题了，请帮助，谢谢。
具体说明下问题

**Comment by tonytan1701** [comment]
请看看是不是用户贡献插件目录名未改为contrib。

**Comment by aylzh** [comment]
> 请看看是不是用户贡献插件目录名未改为contrib。

是这个目录名字，放在/home/pi/.wukong目录下。

**Comment by wzpan** [comment]
依赖装了没？

**Comment by aylzh** [comment]
安装了，把插件拷贝到wukong-robot/plugins目录下可以正常使用。

**Comment by wzpan** [comment]
> 安装了，把插件拷贝到wukong-robot/plugins目录下可以正常使用。

@aylzh 这是错误的做法：通常你不该修改/增删 wukong-robot 下的任何文件，否则这样会导致 wukong-robot 不再能够正常更新。

导致你的 `/home/pi/.wukong/contrib` 下的插件无法正常使用有好几种可能。比如目录不对。比如如果你当前用户是 root ，而你却把 contrib 放在 `/home/pi/.wukong` 下。再比如你多了个目录变成了 `/home/pi/.wukong/contrib/wukong-contrib/` 。再比如你是克隆这个 wukong-contrib 仓库时用了 sudo ，这样这个目录就是 root 用户才能访问……可能性非常多，请自行诊断。

一种辅助方法就是看 log ，有没有加载插件的日志。如果没看到，看看后台管理端的日志页面有没有。找出报错的原因。

**Comment by aylzh** [comment]
谢谢，找到原因了，是因为使用了sudo，所以需要放到root目录下。程序和插件升级到最新版后调用百度音乐插件会报以下错误：
CRITICAL:robot.Brain:Failed to execute plugin
Traceback (most recent call last):
  File "/home/pi/wukong-robot/robot/Brain.py", line 58, in query
    continueHandle = plugin.handle(text, parsed)
  File "/root/.wukong/contrib/BaiduFM.py", line 131, in handle
    music_player.play()
  File "/root/.wukong/contrib/BaiduFM.py", line 33, in play
    self.play_mp3_by_link(path, info)
  File "/root/.wukong/contrib/BaiduFM.py", line 57, in play_mp3_by_link
    self.mic.play(path, True, self.next)
  File "/home/pi/wukong-robot/robot/Conversation.py", line 233, in play
    self.player.play(src, delete, onCompleted=onCompleted, volume=volume)
TypeError: play() got an unexpected keyword argument 'volume'
用一键安装完成后是正常的，升级后报以上错误。这大概是因为插件没有同步升级的原因？

**Comment by aylzh** [comment]
把robot/Conversation.py", line 233
self.player.play(src, delete, onCompleted=onCompleted, volume=volume)
修改为
self.player.play(src, delete, onCompleted=onCompleted)
问题解决，不知道会不会引起其他问题。

**Comment by wzpan** [comment]
@aylzh 的确是bug，已修复。
