### ISSUE TITLE
聊天气泡无法展示camera技能拍的照片

### ISSUE THREAD

**Issue by imliubo** [wzpan/wukong-robot#93]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装

**操作系统**

Raspbian Buster

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**
![image](https://user-images.githubusercontent.com/26544331/66191590-4e679a80-e6c1-11e9-9173-76c919a86efb.png)
camera技能拍的照片无法在气泡中展示，相关保存路径以及摄像头类型均已更改．
![image](https://user-images.githubusercontent.com/26544331/66191760-a0a8bb80-e6c1-11e9-9091-66e47d326444.png)
![image](https://user-images.githubusercontent.com/26544331/66191809-b74f1280-e6c1-11e9-81fa-934af5079d45.png)
照片在目录中是有的．
![image](https://user-images.githubusercontent.com/26544331/66191929-fda47180-e6c1-11e9-977e-990a5932643e.png)
相关配置如下：
![image](https://user-images.githubusercontent.com/26544331/66192083-507e2900-e6c2-11e9-98cb-ea00f1782873.png)
**复现步骤**

之前测试是没问题的，今下午测试出现的，然后更新了一下问题还是一样．

**Comment by wzpan** [comment]
是不是开了代理之类的东西？另外检查下你的 /home/pi/Pictures 目录要有可访问权限。

**Comment by imliubo** [comment]
没有开代理，Pictures目录的权限如下：
![image](https://user-images.githubusercontent.com/26544331/66200841-81fff000-e6d4-11e9-8766-bab0f51f83d5.png)
Pictures目录下是有新照片保存的，至于web界面为什么无法获取不知道．．．

**Comment by imliubo** [comment]
找到原因了．．．是我的疏忽．
![image](https://user-images.githubusercontent.com/26544331/66204134-b5467d00-e6dc-11e9-998e-06b0856515dc.png)
昨天树莓派的ip是192.168.0.5，今天是192.168.0.6，忘记修改后台管理那里的host了，修改好后没问题了．
多谢帮助～

**Comment by wzpan** [comment]
host 那里其实你不需要改都可以。保持 0.0.0.0 。只要保证其他设备访问的时候填对地址即可。

**Comment by imliubo** [comment]
Hi @wzpan ,
刚测试了一下，貌似不改成树莓派在局域网内对应的IP地址，图片就无法显示．
![image](https://user-images.githubusercontent.com/26544331/66212365-5c80df80-e6f0-11e9-9892-ddfd555d4b94.png)
是我还有地方没有设置对吗？我把它改成局域内的IP时是可以正常工作的．
如下图，做了一个简单的植物拍照识别，只有host改成对应的IP是可以显示图片的:
![image](https://user-images.githubusercontent.com/26544331/66212440-7f12f880-e6f0-11e9-84e1-b1f39600114f.png)

**Comment by wzpan** [comment]
哦，如果是在另一台设备要访问，那还是需要设置 host 的。

**Comment by imliubo** [comment]
嗯嗯．
Thanks for help me.

**Comment by icenaive** [comment]
> Hi @wzpan ,
> 刚测试了一下，貌似不改成树莓派在局域网内对应的IP地址，图片就无法显示．
> ![image](https://user-images.githubusercontent.com/26544331/66212365-5c80df80-e6f0-11e9-9892-ddfd555d4b94.png)
> 是我还有地方没有设置对吗？我把它改成局域内的IP时是可以正常工作的．
> 如下图，做了一个简单的植物拍照识别，只有host改成对应的IP是可以显示图片的:
> ![image](https://user-images.githubusercontent.com/26544331/66212440-7f12f880-e6f0-11e9-84e1-b1f39600114f.png)

你好，请问下你这个植物拍照识别是怎么实现的？有这方面的源码可以参考下吗？谢谢

**Comment by imliubo** [comment]
> > Hi @imliubo,
> > 刚测试了一下，貌似不改成树莓派在局域网内对应的IP地址，图片就无法显示．
> > ![image](https://user-images.githubusercontent.com/26544331/66212365-5c80df80-e6f0-11e9-9892-ddfd555d4b94.png)
> > 是我还有地方没有设置对吗？我把它改成局域内的IP时是可以正常工作的．
> > 如下图，做了一个简单的植物拍照识别，只有host改成对应的IP是可以显示图片的:
> > ![image](https://user-images.githubusercontent.com/26544331/66212440-7f12f880-e6f0-11e9-84e1-b1f39600114f.png)
> 
> 你好，请问下你这个植物拍照识别是怎么实现的？有这方面的源码可以参考下吗？谢谢

调用的百度AI的接口，可以参考下我写的这篇文章：
https://www.icxbk.com/article/detail/1129.html

**Comment by icenaive** [comment]
> > > Hi @imliubo,
> > > 刚测试了一下，貌似不改成树莓派在局域网内对应的IP地址，图片就无法显示．
> > > ![image](https://user-images.githubusercontent.com/26544331/66212365-5c80df80-e6f0-11e9-9892-ddfd555d4b94.png)
> > > 是我还有地方没有设置对吗？我把它改成局域内的IP时是可以正常工作的．
> > > 如下图，做了一个简单的植物拍照识别，只有host改成对应的IP是可以显示图片的:
> > > ![image](https://user-images.githubusercontent.com/26544331/66212440-7f12f880-e6f0-11e9-84e1-b1f39600114f.png)
> > 
> > 
> > 你好，请问下你这个植物拍照识别是怎么实现的？有这方面的源码可以参考下吗？谢谢
> 
> 调用的百度AI的接口，可以参考下我写的这篇文章：
> https://www.icxbk.com/article/detail/1129.html

好的，谢谢~
