### ISSUE TITLE
一开始运行时有声音“师父你好”，也能唤醒，但是对话时听不到合成语音。

### ISSUE THREAD

**Issue by unamedzheng** [wzpan/wukong-robot#94]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装

**操作系统**

Linux raspberrypi 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linu

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

具体说明下问题
树莓派3+respeaker2
安装完毕后，可以启动，也能听到试试对我喊唤醒词叫醒我吧。
但是唤醒后交流时听不到声音。无论是使用麦克风对话还是通过后台对话都听不到声音

**Comment by wzpan** [comment]
装了 pulseaudio 和 libsox-fmt-all 没

**Comment by unamedzheng** [comment]
都装了，都是最新的

**Comment by unamedzheng** [comment]
有新发现，如果使用网页控制重启，重启的时候就会把之前的内容一起说出来。好像卡住了的意思。

**Comment by unamedzheng** [comment]
现在是如果用vlc放着歌曲，就可以正常说出内容。先打开vlc放歌，然后重启悟空，就可以正常对话。如果先打开悟空，vlc放歌也没有声音。
之前我禁用了板载的声卡，要不3.5mm口没有声音。

**Comment by HYJJJJJJJJ** [comment]
您好，请问问题解决了嘛？我也遇到了一样的问题，使用的也是树莓派3+respeaker2

**Comment by wzpan** [comment]
问题可能为 alsa 与 pulseaudio 冲突导致。解决办法见：https://github.com/wzpan/wukong-robot/wiki/troubleshooting#%E8%AF%AD%E9%9F%B3%E5%8D%A1%E7%9D%80%E6%92%AD%E6%94%BE%E4%B8%8D%E5%87%BA%E6%9D%A5

**Comment by HYJJJJJJJJ** [comment]
> 问题可能为 alsa 与 pulseaudio 冲突导致。解决办法见：https://github.com/wzpan/wukong-robot/wiki/troubleshooting#%E8%AF%AD%E9%9F%B3%E5%8D%A1%E7%9D%80%E6%92%AD%E6%94%BE%E4%B8%8D%E5%87%BA%E6%9D%A5

困扰了好多天的问题总算解决了！！谢谢大佬！！！！
