### ISSUE TITLE
树莓派4上使用hassio安装wukong插件，无法更新唤醒词

### ISSUE THREAD

**Issue by coolxs945** [wzpan/wukong-robot#95]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

docker安装

**操作系统**

 Raspbian Stretch

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

具体说明下问题
将自己的pmdl文件放置在/root/.wukong/目录下以后，在hassio上点击restart，无法成功启动。
ftp中的配置文件也已经修改。
配置文件如下图：
![1](https://user-images.githubusercontent.com/43312220/69480719-fdfcf580-0e44-11ea-85a6-b5d39f1c1c37.jpg)

错误信息如下图
![2](https://user-images.githubusercontent.com/43312220/69480729-0ce3a800-0e45-11ea-8fa6-6f519e29878c.jpg)

**Comment by PatrickChina** [comment]
这是一个bug，正在着手修复，预计2天内完成

**Comment by coolxs945** [comment]
请问修复了吗？

**Comment by PatrickChina** [comment]
> 请问修复了吗？

fixed，正在撰写最新解释文档

**Comment by coolxs945** [comment]
请问在哪里更新了？找了一大圈没找到
