### ISSUE TITLE
启动时报错 ``` Backtrace has not been implemented yet. ```

### ISSUE THREAD

**Issue by MirrorCY** [wzpan/wukong-robot#97]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

docker安装

**操作系统**

Raspbian Buster

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

在~/.wukong/custom/ 目录下新建了 helloWorrld.py 后，重启wukong 启动时报错
```
root@e5f5e72c86a4:~/wukong-robot# python3 wukong.py

********************************************************
*          wukong-robot - 中文语音对话机器人           *
*          (c) 2019 潘伟洲 <m@hahack.com>              *
*     https://github.com/wzpan/wukong-robot.git        *
********************************************************

            后台管理端：http://0.0.0.0:5000
            如需退出，可以按 Ctrl-4 组合键


/muse/enable not specified in profile, defaulting to 'False'
ERROR (Input():snowboy-io.cc:315) Fail to open input file "/root/.wukong/你好小联.pmdl"
terminate called after throwing an instance of 'std::runtime_error'
  what():  ERROR (Input():snowboy-io.cc:315) Fail to open input file "/root/.wukong/你好小联.pmdl"

[stack trace: ]
Backtrace has not been implemented yet.

Aborted (core dumped)
```
helloWorld.py 文件内容是拷贝的文档中的

**Comment by MirrorCY** [comment]
删除helloWorld.py 后启动仍然报错

**Comment by MirrorCY** [comment]
破案了，重启docker会清空数据

**Comment by MirrorCY** [comment]
建议写在文档里，多数新人以前应该没用过Docker，最好优化一下Docker安装流程让大家不会像我这样憨憨的配置好后清空数据555

**Comment by wzpan** [comment]
在 [AnyQ 配置](https://wukong.hahack.com/#/anyq?id=qa-%e9%9b%86%e9%85%8d%e7%bd%ae%ef%bc%88gui-%e6%96%b9%e5%bc%8f%ef%bc%89)一节我有提到：

![image](https://user-images.githubusercontent.com/1631405/70390889-3803f500-1a0a-11ea-8f6d-275cefc46857.png)

不过，唤醒词建议是放在 ~/.wukong 目录里，这个目录完全可以挂载为系统里的一个目录，这样就不会在重启后被修改。

已修改文档。

**Comment by MirrorCY** [comment]
感谢回复，使用docker时第一印象会把他当做虚拟机，按虚拟机的逻辑使用。
然后文档里的启动命令是从镜像启动，每次都会新建一个容器，有什么更好的方法吗

---原始邮件---
发件人: "潘伟洲"<notifications@github.com&gt;
发送时间: 2019年12月8日(周日) 晚上10:42
收件人: "wzpan/wukong-robot"<wukong-robot@noreply.github.com&gt;;
抄送: "MirrorCY"<1358688418@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [wzpan/wukong-robot] 启动时报错 ``` Backtrace has not been implemented yet. ``` (#97)



在 AnyQ 配置一节我有提到：
 

 
不过，唤醒词建议是放在 ~/.wukong 目录里，这个目录完全可以挂载为系统里的一个目录，这样就不会在重启后被修改。
 
已修改文档。

**Comment by MirrorCY** [comment]
感谢回复，使用docker时第一印象会把他当做虚拟机，按虚拟机的逻辑使用。
然后文档里的启动命令是从镜像启动，每次都会新建一个容器，有什么更好的方法吗
