### ISSUE TITLE
能不能把服务装在云上，本地只提供录音和放音

### ISSUE THREAD

**Issue by kekemuyu** [wzpan/wukong-robot#98]
wukong-robot能不能只提供如标题说的，wukong-robot不装在本地，装在云上，把api全部暴露出来供终端调用，这样本地硬件可以简单到只要有个客户端就行了。这样能适用更多的硬件，即使不带操作系统都可以如esp32

**Comment by wzpan** [comment]
支持啊。http://bot.hahack.com 就是放云上的。[api](https://bot.hahack.com/api) 也都暴露了。

``` bash
➜  chatting git:(master) curl bot.hahack.com:5000/gethistory?validate=f4bde2a342c7c75aa276f78b26cfbd8a 
{"message": "ok", "history": "[{\"uuid\": \"ea421e0c-1af7-11ea-a526-0242ac110006\", \"type\": 1, \"text\": \"\\u5e08\\u7236 \\u4f60\\u597d\\uff01\\u8bd5\\u8bd5\\u5bf9\\u6211\\u558a\\u5524\\u9192\\u8bcd\\u53eb\\u9192\\u6211\\u5427\", \"time\": \"2019-12-10 02:51:07\"}]", "code": 0}% 
```

**Comment by kekemuyu** [comment]
> 支持啊。http://bot.hahack.com 就是放云上的。[api](https://bot.hahack.com/api) 也都暴露了。
> 
> ```shell
> ➜  chatting git:(master) curl bot.hahack.com:5000/gethistory?validate=f4bde2a342c7c75aa276f78b26cfbd8a 
> {"message": "ok", "history": "[{\"uuid\": \"ea421e0c-1af7-11ea-a526-0242ac110006\", \"type\": 1, \"text\": \"\\u5e08\\u7236 \\u4f60\\u597d\\uff01\\u8bd5\\u8bd5\\u5bf9\\u6211\\u558a\\u5524\\u9192\\u8bcd\\u53eb\\u9192\\u6211\\u5427\", \"time\": \"2019-12-10 02:51:07\"}]", "code": 0}% 
> ```

太棒了，这么重要的功能，为什么没在安装教程中看到，我还以为不支持呢？应该重点介绍一下，哈哈~。迫不及待想写个客户端试一下，刚点了一下api的那个连接，需要登陆，这个是需要注册吗？没看到注册的连接

**Comment by wzpan** [comment]
这是 wukong-robot 默认的账号。

账号名：wukong
密码：wukong@2018

其实就是在云端 docker 安装一个 wukong-robot 。

**Comment by kekemuyu** [comment]
这种cs模式还支持语音唤醒吗？我指的是本地还能否硬件还能否支持语音唤醒，是不是还得装语音唤醒之类的软件

**Comment by wzpan** [comment]
API 更适合用于自行开发一个其他类型的交互的客户端，例如之前（但可能已不能工作）的微信机器人，或者自行开发一个文本型对话机器人客户端、小程序等。

如果还要离线唤醒，为什么不直接把服务搭到本地然后做个内网穿透？

**Comment by kekemuyu** [comment]
感谢耐心答复，了解了
