### ISSUE TITLE
启动 docker 镜像报错

### ISSUE THREAD

**Issue by YH-Chow** [wzpan/wukong-robot#99]
树莓派4B启动docker镜像命令报错
pi@raspberrypi:~/wukong-robot-pi-installer $ docker run -it -p 5000:5000 --device /dev/snd -e LANG=C.UTF-8 wzpan/wukong-robot-arm:latest
docker: unknown server OS: .
See 'docker run --help'.
请问命令该怎么修改还是其他的原因

**Comment by wzpan** [comment]
看这样子，你的设备的docker无法识别树莓派4B的板子，应该是docker-ce还没有兼容树莓派4B。
耐心等兼容吧。

**Comment by YH-Chow** [comment]
哦，好的谢谢

**Comment by wzpan** [comment]
@YH-Chow 我用buster系统试了下，不带sudo也遇到了这个问题。带了sudo就好了。

![image](https://user-images.githubusercontent.com/1631405/71547890-bbe54780-29e0-11ea-8a4e-5da58be41e84.png)

**Comment by YH-Chow** [comment]
@wzpan 我试了一下，成功了，十分感谢
